plentymarkets/terra-components

src/app/forms/select-box/plenty-select-box.component.scss, src/app/forms/select-box/plenty-select-box.component.ts
=> Select box

src/app/pager/plenty-pager.component.html, src/app/pager/plenty-pager.component.scss, src/app/pager/plenty-pager.component.ts
=> Plenty pager

src/app/infobox/plenty-infobox.component.html, src/app/infobox/plenty-infobox.component.scss
=> fix styles for infobox

src/app/alert/plenty-alert-panel.component.ts
=> alert_panel_fix

src/app/button/plenty-button.component.scss, src/app/forms/input/plenty-input.component.scss, src/app/forms/multi-select-box/plenty-multi-select-box.component.html, src/app/forms/multi-select-box/plenty-multi-select-box.component.scss, src/app/forms/select-box/plenty-select-box.component.scss, src/app/infobox/plenty-infobox.component.scss, src/app/pager/plenty-pager.component.scss, src/app/taglist/plenty-taglist.component.html
=> changed styles for components

src/app/forms/multi-select-box/plenty-multi-select-box.component.scss
=> fix_multi_select_box

src/app/filter/plenty-filter.component.html, src/app/filter/plenty-filter.component.scss
@nappynapster, @vwiebe, border color war unpassend; habe es gleich aus inline heraus genommen und in scss-Datei gepackt
=> filter_style_fix

src/app/forms/multi-select-box/plenty-multi-select-box.component.scss
=> style_fix_msb

LICENSE.md, README.md
=> ADD license and update readme

src/app/app.module.ts, src/app/dcl-wrapper/plenty-dcl-wrapper.component.ts, src/app/dynamic-module-loader/plenty-dynamic-module-loader.component.html, src/app/dynamic-module-loader/plenty-dynamic-module-loader.component.ts, src/app/split-view/plenty-split-view.component.html
=> split_view

src/app/portlet/plenty-portlet.component.html, src/app/portlet/plenty-portlet.component.scss, src/app/portlet/plenty-portlet.component.ts, src/app/regex/plenty-regex.ts, src/app/service/base.service.ts
@PascalWess, @MFrank84, @nappynapster ✌️
=> portlet_regex_service_shared

src/app/taglist/plenty-taglist.component.html, src/app/taglist/plenty-taglist.component.scss, src/app/taglist/plenty-taglist.component.ts, src/app/toolbar/base-toolbar/plenty-base-toolbar.component.html, src/app/toolbar/base-toolbar/plenty-base-toolbar.component.scss, src/app/tree/base/plenty-base-tree.component.ts, src/app/tree/checkbox-tree/plenty-checkbox-tree.component.html, src/app/tree/checkbox-tree/plenty-checkbox-tree.component.ts, src/app/tree/leaf/plenty-leaf.component.ts, src/app/tree/plenty-tree.component.html, src/app/tree/plenty-tree.component.scss, src/app/tree/plenty-tree.component.ts
@vwiebe, @vwiebe2, @nappynapster, @PascalWess ✌️
=> taglist_toolbar_tree

src/app/split-view/data/plenty-split-view-data.ts, src/app/split-view/plenty-split-view.component.html, src/app/split-view/plenty-split-view.component.scss, src/app/split-view/plenty-split-view.component.ts, src/app/table/cell/plenty-table-cell.ts, src/app/table/cell/plenty-table-header-cell.ts, src/app/table/data-table/context-menu/directive/plenty-data-table-context-menu.directive.ts, src/app/table/data-table/context-menu/interface/plenty-data-table-context-menu-entry.ts, src/app/table/data-table/context-menu/plenty-data-table-context-menu.component.html, src/app/table/data-table/context-menu/plenty-data-table-context-menu.component.scss, src/app/table/data-table/context-menu/plenty-data-table-context-menu.component.ts, src/app/table/data-table/context-menu/service/plenty-data-table-context-menu.service.ts, src/app/table/data-table/plenty-data-table.component.html, src/app/table/data-table/plenty-data-table.component.scss, src/app/table/data-table/plenty-data-table.component.ts, src/app/tag/plenty-tag.component.html, src/app/tag/plenty-tag.component.scss, src/app/tag/plenty-tag.component.ts
@PascalWess, @vwiebe2, @MFrank84 ✌️
=> splitview_table_tag_folder

src/app/loading-bar/event/plenty-loading-bar-event.ts, src/app/loading-bar/plenty-loading-bar.component.html, src/app/loading-bar/plenty-loading-bar.component.scss, src/app/loading-bar/plenty-loading-bar.component.ts, src/app/overlay/plenty-overlay.component.html, src/app/overlay/plenty-overlay.component.ts, src/app/pager/plenty-pager.component.html, src/app/pager/plenty-pager.component.scss, src/app/pager/plenty-pager.component.ts
@nappynapster, @MFrank84, @vwiebe
=> loadingbar_overlay_pager

src/app/forms/checkbox/plenty-checkbox.component.html, src/app/forms/checkbox/plenty-checkbox.component.scss, src/app/forms/checkbox/plenty-checkbox.component.ts, src/app/forms/input/double-input/plenty-double-input.component.html, src/app/forms/input/double-input/plenty-double-input.component.ts, src/app/forms/input/number-input/plenty-number-input.component.html, src/app/forms/input/number-input/plenty-number-input.component.ts, src/app/forms/input/plenty-input.component.scss, src/app/forms/input/plenty-input.component.ts, src/app/forms/input/text-input/plenty-text-input.component.html, src/app/forms/input/text-input/plenty-text-input.component.ts, src/app/forms/multi-select-box/plenty-multi-select-box.component.html, src/app/forms/multi-select-box/plenty-multi-select-box.component.scss, src/app/forms/multi-select-box/plenty-multi-select-box.component.ts, src/app/forms/multi-select-box/value/plenty-multi-select-box-value.ts, src/app/forms/select-box/plenty-select-box.component.scss, src/app/forms/select-box/plenty-select-box.component.ts, src/app/indicator/plenty-indicator.component.html, src/app/indicator/plenty-indicator.component.scss, src/app/indicator/plenty-indicator.component.ts, src/app/infobox/plenty-infobox.component.html, src/app/infobox/plenty-infobox.component.scss, src/app/infobox/plenty-infobox.component.ts
@nappynapster, @MFrank84, @vwiebe, @PascalWess
=> forms_indicator_infobox

src/app/dcl-wrapper/plenty-dcl-wrapper.component.html, src/app/dcl-wrapper/plenty-dcl-wrapper.component.ts, src/app/filter/plenty-filter.component.html, src/app/filter/plenty-filter.component.scss, src/app/filter/plenty-filter.component.ts
@MFrank84, @vwiebe, @PascalWess
=> data_dcl_filter

src/app/alert/plenty-alert-panel.component.html, src/app/dcl-wrapper/plenty-dcl-wrapper.component.ts, src/app/forms/checkbox/plenty-checkbox.component.html, src/app/forms/checkbox/plenty-checkbox.component.ts, src/app/forms/input/double-input/plenty-double-input.component.html, src/app/forms/input/number-input/plenty-number-input.component.html, src/app/forms/input/text-input/plenty-text-input.component.html, src/app/forms/multi-select-box/plenty-multi-select-box.component.html, src/app/forms/multi-select-box/plenty-multi-select-box.component.ts, src/app/forms/select-box/plenty-select-box.component.html, src/app/loading-bar/plenty-loading-bar.component.html, src/app/table/data-table/plenty-data-table.component.html
@nappynapster, @MFrank84, @vwiebe
=> fix_attributes

src/app/dynamic-module-loader/terra-dynamic-module-loader.component.ts, src/app/split-view/data/terra-split-view.interface.ts, src/app/split-view/terra-split-view.component.html, src/app/split-view/terra-split-view.component.scss, src/app/split-view/terra-split-view.component.ts
- updated split view naming
- fixed dynamic module loader
@vwiebe, @nappynapster, @MFrank84
=> split view

src/app/forms/input/double-input/terra-double-input.component.ts, src/app/forms/input/number-input/terra-number-input.component.ts, src/app/forms/input/text-input/terra-text-input.component.ts
@vwiebe @nappynapster @dantrau
=> input values for inputs

src/app/dynamic-module-loader/terra-dynamic-module-loader.component.ts, src/app/split-view/data/terra-split-view.interface.ts, src/app/split-view/terra-split-view.component.html, src/app/split-view/terra-split-view.component.ts
@nappynapster, @vwiebe, @Neill83
=> fix_dynamic_module_loader

src/app/forms/checkbox/terra-checkbox.component.html, src/app/forms/checkbox/terra-checkbox.component.ts, src/app/forms/multi-select-box/terra-multi-select-box.component.html, src/app/forms/multi-select-box/terra-multi-select-box.component.ts, src/app/forms/select-box/terra-select-box.component.html
@nappynapster @vwiebe @MFrank84 @dantrau
=> fixed multiselect

src/app/tree/base/terra-base-tree.component.ts, src/app/tree/leaf/terra-leaf.interface.ts, src/app/tree/terra-tree.component.html, src/app/tree/terra-tree.component.scss
@vwiebe @MFrank84 @nappynapster @dantrau
=> added clickfunction to tree-leaf

src/app/dynamic-module-loader/terra-dynamic-module-loader.component.ts, src/app/terra-components.module.ts
=> fix_module_loader

gulpfile.js, package.json
add gulp script for locally build and deployment direct to terra/node_modules/@plentymarekts/terra-components
use only for local testing purposes
@Neill83 @vwiebe @dantrau @nappynapster
=> add gulp script for locally build

src/app/forms/select-box/terra-select-box.component.ts
- InputSelect to get/set selected value of select box
=> - added selectedValue Input

src/app/tag/terra-tag.component.html, src/app/tag/terra-tag.component.ts
@vwiebe, @nappynapster, @MFrank84
=> tag_component

src/app/filter/terra-filter.component.html
@zhajjhassan, @MFrank84, @nappynapster
=> filter_component

src/app/split-view/terra-split-view.component.html, src/app/split-view/terra-split-view.component.scss
@vwiebe, @nappynapster, @MFrank84
=> split_view_sizing

src/app/split-view/terra-split-view.component.ts
@MFrank84, @vwiebe, @nappynapster
=> split_view_changes

src/app/split-view/terra-split-view.component.html
commented out copy to clipboard button
=> copy_to_clipboard

src/app/table/data-table/terra-data-table.component.scss, src/app/table/data-table/terra-data-table.component.ts, src/app/terra-components.component.scss, src/app/terra-components.module.ts
@nappynapster @dantrau @vwiebe
=> null check for rowlist

src/app/filter/terra-filter.component.html, src/app/filter/terra-filter.component.ts
=> FIX removed labels from search/reset and replaced with icons

src/index.glob.scss
=> fix global overflow

src/app/pager/data/terra-pager.interface.ts, src/app/pager/terra-pager.component.html, src/app/pager/terra-pager.component.ts
=> FIX changed keys of pager interface

src/app/tree/base/terra-base-tree.component.ts, src/app/tree/leaf/terra-leaf.interface.ts, src/app/tree/terra-tree.component.html
- added color for leaf icon
ich brauch farben und das die Leafs sich nicht öffnen onClick...
=> - possibility to avoid open leaf on click

src/app/tree/base/terra-base-tree.component.ts, src/app/tree/leaf/terra-leaf.interface.ts, src/app/tree/terra-tree.component.html
@plentymarkets/team-terra brauch noch ne function die getriggert wird wenn man das leaf öffnet
=> implemented a function to trigger when leaf is opened

src/app/tree/base/terra-base-tree.component.ts, src/app/tree/leaf/terra-leaf.interface.ts, src/app/tree/terra-tree.component.html
syntax angepasst für den style
@plentymarkets/team-terra bitte dann sofort verteilen und bescheid geben, danke
=> changed style according to ng2

src/app/filter/terra-filter.component.html, src/app/filter/terra-filter.component.scss
=> updated filter styling

src/app/table/data-table/terra-data-table.component.ts
=> FIX code formatting & added validation

src/app/tree/terra-tree.component.scss
=> fixed tree padding

src/app/split-view/terra-split-view.component.html, src/app/split-view/terra-split-view.component.scss
=> update splitview styles

src/app/split-view/terra-split-view.component.scss
@plentymarkets/team-terra, @Neill83
=> update splitview styling

src/app/button/terra-button.component.scss
=> fixed vertical button group

src/app/button/terra-button.component.scss
=> fix vertical button group

src/app/info-box/terra-info-box.component.html, src/app/info-box/terra-info-box.component.scss, src/index.glob.scss
=> fixed infobox and global column paddings

src/app/info-box/terra-info-box.component.scss
=> fix infobox height

src/app/indicator/terra-indicator.component.html, src/app/indicator/terra-indicator.component.ts
fixed component’s usage of style classes
=> indicator_styling

src/app/table/data-table/terra-data-table.component.scss
=> made tables responsive

src/app/table/data-table/terra-data-table.component.scss
=> update table styles

src/app/forms/input/date-picker/terra-date-picker.component.scss
=> styled datepicker

src/app/table/data-table/terra-data-table.component.scss
=> fixed table colors

src/app/tile/panel/terra-tile-box-panel.component.html
=> changed boolean for showing tile-view first

src/app/forms/select-box/terra-select-box.component.html
=> FIXED active value

src/app/split-view/terra-split-view.component.html, src/app/split-view/terra-split-view.component.scss
=> breadcrumb_styling

src/app/dynamic-module-loader/terra-dynamic-module-loader.component.ts, src/app/loading-spinner/service/terra-loading-spinner.service.ts, src/app/loading-spinner/terra-loading-spinner.component.html, src/app/loading-spinner/terra-loading-spinner.component.scss, src/app/loading-spinner/terra-loading-spinner.component.ts, src/app/service/terra-base.service.ts, src/app/terra-components.module.ts, src/index.ts
=> NEW loading spinner

src/app/button/terra-button.component.scss, src/app/filter/terra-filter.component.html, src/app/filter/terra-filter.component.scss, src/app/forms/input/date-picker/terra-date-picker.component.scss, src/app/forms/input/double-input/terra-double-input.component.scss, src/app/forms/input/terra-input.component.scss, src/app/forms/input/text-area-input/terra-text-area-input.component.html, src/app/forms/input/text-area-input/terra-text-area-input.component.scss
=> fixed and refactored all inputs

src/app/split-view/terra-split-view.component.html, src/app/split-view/terra-split-view.component.scss
=> breadcrumb styling

src/app/filter/terra-filter.component.html, src/app/filter/terra-filter.component.ts
=> add_form_to_filter

src/app/service/data/terra-url-params-decorator.service.ts, src/app/terra-components.module.ts
=> ADD - TerraUrlParamsDecorator

src/app/resources/locale_de.json, src/app/resources/locale_en.json, src/app/table/data-table/terra-data-table.component.html, src/app/table/data-table/terra-data-table.component.scss, src/app/table/data-table/terra-data-table.component.ts
- added initial message to the data table
- todo: implement translation after update to angular 4.0
=> sprint_13_03_17/tasks/add_initial_message_to_datatable

src/app/forms/input/double-input/terra-double-input.component.ts, src/app/forms/input/number-input/terra-number-input.component.ts, src/app/forms/input/text-area-input/terra-text-area-input.component.ts, src/app/forms/input/text-input/terra-text-input.component.ts
=> FIX refactor input forms

CHANGELOG.md
=> UPDATED changelog

src/app/terra-components.module.ts, src/app/toggle/terra-toggle.component.html, src/app/toggle/terra-toggle.component.scss, src/app/toggle/terra-toggle.component.ts
=> ADD - toggle component

src/app/toggle/terra-toggle.component.scss
=> FIX - toggle button position

src/app/navigator/button-group/data/terra-button-group.interface.ts, src/app/navigator/button-group/terra-button-group.component.html, src/app/navigator/button-group/terra-button-group.component.scss, src/app/navigator/button-group/terra-button-group.component.ts, src/index.ts
=> NEW show collapse icon if children are given

src/app/tag/data/terra-tag.interface.ts
=> changed tag interface

src/app/forms/input/date-picker/terra-date-picker.component.scss, src/app/forms/input/date-picker/terra-date-picker.component.ts
=> FIXED date picker icons

src/app/alert/terra-alert-panel.component.html
=> FIXED html tags in alert messages

src/app/button/terra-button.component.scss, src/app/navigator/button-group/terra-button-group.component.scss
=> fixed, restyled and refactored buttons

src/app/info-box/terra-info-box.component.scss
=> FIXED height of infobox inner

src/app/button/terra-button.component.scss, src/app/navigator/button-group/terra-button-group.component.html, src/app/navigator/button-group/terra-button-group.component.scss, src/app/navigator/terra-navigator.component.scss
=> added generic button group for menus

src/app/service/terra-base.service.ts
to get error status from response
=> error_status_from_response

src/app/forms/select-box/terra-select-box.component.html
=> ADDED empty value option to select box

src/app/forms/input/date-picker/terra-date-picker.component.html, src/app/forms/input/date-picker/terra-date-picker.component.ts
Reverts plentymarkets/terra-components#187
Note: Because of breaking changes
=> Revert "Fix/datepicker"

src/app/button/terra-button.component.scss
=> vertical menu divider styles

src/app/button/terra-button.component.scss
=> re-styled context menu divider

src/app/table/data-table/context-menu/terra-data-table-context-menu.component.html
=> fix: hide data table context menu if option list is empty

src/app/split-view/multi/terra-multi-split-view.component.html, src/app/split-view/multi/terra-multi-split-view.component.ts
* use the module index to identify the module to select and to slide the viewport to
=> fix: undefined anchor error

src/index.glob.scss
=> feature: animate column width changes

src/app/forms/select-box/terra-select-box.component.ts
=> feature: public getter and setter for select box's isValid property

src/app/assets/styles/_variables.scss, src/app/toolbar/base-toolbar/terra-base-toolbar.component.html, src/app/toolbar/base-toolbar/terra-base-toolbar.component.scss, src/app/toolbar/base-toolbar/terra-base-toolbar.component.ts
=> ADDED input for setting the toolbar sticky

src/app/split-view/multi/terra-multi-split-view.component.ts
=> fix: (multi-split-view) update viewport after window resizing

src/app/split-view/multi/terra-multi-split-view.component.ts
=> feature: (multi-split-view) disable horizontal scroll animation option

CHANGELOG.md, src/app/forms/suggestion-box/terra-suggestion-box.component.html
=> suggestion box allow html parsing

CHANGELOG.md
=> fix: added missing change logs

src/app/split-view/multi/terra-multi-split-view.component.ts
=> hotfix: nullpointer when opening the tab with a multi split view

CHANGELOG.md, src/app/split-view/multi/terra-multi-split-view.component.scss
=> FIX removed animation to fit needs of plugin

CHANGELOG.md, gulpfile.js, src/app/dynamic-module-loader/data/terra-dynamic-loaded-component-input.interface.ts, src/app/dynamic-module-loader/data/terra-split-view-component.interface.ts, src/app/dynamic-module-loader/terra-dynamic-module-loader.component.ts, src/app/forms/suggestion-box/terra-suggestion-box.component.html, src/app/portlet/terra-portlet.component.html, src/app/portlet/terra-portlet.component.scss, src/app/portlet/terra-portlet.component.ts, src/app/service/data/exception.interface.ts, src/app/service/terra-base.service.ts, src/app/split-view/multi/data/terra-multi-split-view.config.ts, src/app/split-view/multi/data/terra-multi-split-view.interface.ts, src/app/split-view/multi/terra-multi-split-view.component.html, src/app/split-view/multi/terra-multi-split-view.component.scss, src/app/split-view/multi/terra-multi-split-view.component.ts, src/app/terra-components.module.ts
=> merge: beta7 into beta7_zlk_release

src/app/pager/terra-pager.component.html
deactivate buttons if invalid values are used
constrain max value of number input for current page
=> FIX constraints for pager

src/app/split-view/multi/data/terra-multi-split-view.config.ts, src/app/split-view/multi/terra-multi-split-view.component.ts
depends on https://github.com/plentymarkets/terra/pull/351
=> fix: revert multi split view changes when removing a view.

src/app/pager/terra-pager.component.html, src/app/pager/terra-pager.component.ts
disable all buttons and inputs when pager is not initialised
=> Fix disable all buttons and inputs when pager is not initialised

CHANGELOG.md, src/app/forms/select-box/terra-select-box.component.scss, src/app/forms/suggestion-box/terra-suggestion-box.component.html, src/app/forms/suggestion-box/terra-suggestion-box.component.ts
add possibility to..
* navigate through the list of suggestions with the `arrow keys`
* select a suggestion value with `Enter`
* close the dropdown of suggested values with `Escape`
**Testing**: This feature can be tested on all suggestion boxes, e.g. in the ng2-showcase or in the log-filter.
=> feature (suggestion box): navigate with arrow keys

CHANGELOG.md, src/app/forms/suggestion-box/terra-suggestion-box.component.html, src/app/forms/suggestion-box/terra-suggestion-box.component.ts
**Testing**: This feature can be tested on all suggestion boxes, e.g. in the ng2-showcase or in the log-filter.
=> feature (suggestion box): select complete input text when focused

CHANGELOG.md, src/app/assets/lang/locale-de.json, src/app/assets/lang/locale-en.json, src/app/forms/select-box/terra-select-box.component.scss, src/app/forms/suggestion-box/terra-suggestion-box.component.html, src/app/forms/suggestion-box/terra-suggestion-box.component.ts
new optional input `inputWithRecentlyUsed` that enables a list of 'recently used elements' to be shown if no input (less than 3 chars) is provided
**Testing**: This feature can be tested on all suggestion boxes, e.g. in the ng2-showcase or in the log-filter.
=> feature (suggestion box): recently used elements

CHANGELOG.md, src/app/forms/suggestion-box/terra-suggestion-box.component.ts
=> feature (suggestion box): allow space separated list of search strings

src/app/split-view/multi/terra-multi-split-view.component.scss
FIX case for plugins
FIX adapted animation height offset of new design
=> FIX adapted animation height offset of new design

src/app/table/data-table/row/terra-data-table-row.interface.ts, src/app/table/data-table/terra-data-table.component.html, src/app/table/data-table/terra-data-table.component.ts
=> UPDATE data-table with checkbox clicked event

CHANGELOG.md, src/app/service/terra-base.service.ts
provide this generic functionality to every service that is implemented in https://github.com/plentymarkets/terra
**Caution**: Do not merge before https://github.com/plentymarkets/terra/pull/374
=> feature (base-service): append given parameters to a given url

CHANGELOG.md, src/app/split-view/multi/data/terra-multi-split-view.config.ts, src/app/split-view/multi/terra-multi-split-view.component.ts
=> feature (multi-split-view): manually select a specific view via the split view config

src/app/forms/suggestion-box/terra-suggestion-box.component.ts, src/app/navigator/terra-navigator.component.html, src/app/navigator/terra-navigator.component.ts
depends on: https://github.com/plentymarkets/terra/pull/382
=> feature (navigator, suggestion-box): add possibility to insert a component

src/app/button/terra-button.component.html, src/app/button/terra-button.component.scss, src/app/button/terra-button.component.ts
=> fix (button): disabled state

src/app/table/data-table/terra-data-table.component.html
=> fix (data-table): icon and text in the same cell

CHANGELOG.md, src/app/split-view/multi/data/terra-multi-split-view.config.ts
=> feature (mulit-split-view): prevent adding two views with the same name in one hierarchy level

CHANGELOG.md, src/app/pager/terra-pager.component.ts, src/app/table/data-table/terra-data-table.component.html, src/app/table/data-table/terra-data-table.component.ts
**caution**: do not merge before https://github.com/plentymarkets/terra-components/pull/287
=> feature (data-table, pager): debounce paging

src/app/filter/terra-filter.component.html
=> Changed contact filter search button color.

src/app/table/simple/terra-simple-table.component.html
see https://github.com/plentymarkets/terra/pull/415
=> FIX icons in simple table

src/app/portlet/terra-portlet.component.html, src/app/portlet/terra-portlet.component.scss, src/app/portlet/terra-portlet.component.ts
- change style of portlet in portlet to default portlet style
- disable portlet head if no header was given
=> portlet changes

CHANGELOG.md, src/app/forms/select-box/terra-select-box.component.ts
=> Fixed deselect of select boxes when clicking on another select box.

src/app/dynamic-module-loader/terra-dynamic-module-loader.component.ts
=> pass changes to assigned input properties to dynamic component instance

src/app/split-view/multi/terra-multi-split-view.component.scss
Mergen und verteilen im der Verteilung des Fullscreen Button branches
=> - change css selector

src/app/forms/input/terra-input.component.scss, src/app/pager/terra-pager.component.scss
This **globally** removes the spin button from all inputs of type number
=> fix (number-input): remove spin buttons from inputs of type number

src/index.glob.scss
.. in order to resolve the variables
=> hotfix: import '_variables.scss' to global stylesheet

src/app/pager/terra-pager.component.scss
=> fix (pager): update style for page input

CHANGELOG.md, src/app/pager/terra-pager.component.ts
=> fix (pager): limit page number input to a valid range

src/app/assets/lang/locale-de.json, src/app/split-view/multi/terra-multi-split-view.component.html, src/app/split-view/multi/terra-multi-split-view.component.scss, src/index.glob.scss
FIX body background-color
DELTE div & style class in multi-split-view
=> FIX styling

src/app/assets/styles/_variables.scss
=> Added backend header height variables

src/app/table/simple/terra-simple-table.component.ts
=> Emit rowClicked when pressing Enter key

CHANGELOG.md, src/app/table/data-table/terra-data-table.component.html
=> Team terra/act customer/data table header tooltips

src/index.ts
=> FIX add missing export for terra-slider

CHANGELOG.md, src/app/no-result/terra-no-result-notice.component.ts, src/app/table/data-table/terra-data-table.component.html
=> Use new no result notice selector.

src/app/split-view/multi/terra-multi-split-view.component.ts
=> fix (multi-split-view): problems with view selection after view deletion

src/app/forms/radio-button/terra-radio-button.component.scss
related to https://trello.com/c/sdYcDnCd
=> FIX radio button seems to be checked in disabled state

CHANGELOG.md, src/app/taglist/terra-taglist.component.ts
=> fix (tag-list): replace interface

CHANGELOG.md
... for https://github.com/plentymarkets/terra-components/pull/354
=> fix (multi-split-view): missing changelog

CHANGELOG.md, src/app/table/data-table/cell/terra-data-table-cell.interface.ts, src/app/table/data-table/cell/terra-data-table-text.interface.ts, src/app/table/data-table/cell/terra-ref-type.interface.ts, src/app/table/data-table/terra-data-table.component.html, src/app/table/data-table/terra-data-table.component.ts, src/app/tag/terra-tag.component.scss, src/index.ts
=> fix (data-table): refactor cell interface

CHANGELOG.md, src/app/button/enum/button-color.enum.ts, src/app/table/data-table/context-menu/data/terra-data-table-context-menu-entry.interface.ts, src/app/table/data-table/context-menu/terra-data-table-context-menu.component.html
added button color to context menu entries
=> added enum for button colors

CHANGELOG.md, src/app/forms/input/double-input/terra-double-input.component.html, src/app/forms/input/number-input/terra-number-input.component.html, src/app/forms/input/text-input/terra-text-input.component.html
=> fix (inputs): show label if value is 0

CHANGELOG.md, src/app/forms/input/terra-input.component.scss, src/app/forms/suggestion-box/terra-suggestion-box.component.html, src/app/forms/suggestion-box/terra-suggestion-box.component.scss
=> added disabled style to suggestion box

CHANGELOG.md, src/app/forms/checkbox/terra-checkbox.component.html, src/app/forms/checkbox/terra-checkbox.component.ts
=> added unique ids to checkbox

CHANGELOG.md, src/app/forms/select-box/terra-select-box.component.scss
=> fix (select box): missing red border if select box value is invalid

src/app/info-box/terra-info-box.component.html, src/app/info-box/terra-info-box.component.scss, src/app/info-box/terra-info-box.component.ts
=> Make footer optional

CHANGELOG.md, src/app/forms/input/double-input/terra-double-input.component.html, src/app/forms/input/number-input/terra-number-input.component.html, src/app/forms/input/text-input/terra-text-input.component.html
=> fix (inputs): make required state visible when no value is set

src/app/forms/input/double-input/terra-double-input.component.html, src/app/forms/input/double-input/terra-double-input.component.ts
NEW input[type:number] has now a dynamical calculated step attribute
@Neill83
=> NEW input parameter "inputDecimalCount" for double precision

src/app/forms/checkbox/terra-checkbox.component.scss
=> -FIX remove coloring of the checkbox content

src/app/helpers/terra-pdf.helper.ts, src/app/service/terra-base-service.helper.ts, src/app/table/data-table/terra-data-table.component.html, src/app/table/data-table/terra-data-table.component.ts, src/app/terra-components.module.ts, src/index.ts
FIX parameter for onGroupFunctionExecuteButtonClicked Event
=> FIX naming

package.json
=> release: v2.1.41-zlk

src/app/components/alert/terra-alert.component.ts, src/app/components/forms/checkbox/terra-checkbox.component.ts, src/app/components/forms/input/terra-input.component.ts, src/app/components/forms/radio-button/terra-radio-button.component.ts, src/app/components/forms/select-box/terra-select-box.component.html, src/app/components/forms/select-box/terra-select-box.component.ts, src/app/components/forms/suggestion-box/terra-suggestion-box.component.html, src/app/components/forms/suggestion-box/terra-suggestion-box.component.ts, src/app/components/split-view/data/terra-split-config-base.ts, src/app/components/split-view/multi/data/terra-multi-split-view.config.ts, src/app/components/tables/data-table/terra-data-table.component.html, src/app/components/tables/data-table/terra-data-table.component.ts, src/app/components/tile/panel/terra-tile-box-panel.component.ts
@plentymarkets/terra-admins  Zu guter letzte noch ein PR für die Components. Bin gespannt ob ich alles berücksichtigt habe.
=> Remove redundant getter and setter

src/app/components/tree/node-tree/data/terra-node.interface.ts, src/app/components/tree/node-tree/node/terra-node.component.html, src/app/components/tree/node-tree/node/terra-node.component.ts
=> - tooltip in node tree

src/app/service/terra-base.service.ts
=> fix (base-service): do not add empty params to url

gulpfile.js, src/app/components/tables/data-table/terra-data-table.component.scss
=> fix (data-table): changed appearance of links in tables

gulp.config.js
=> Ignore .d.ts-files in src folder when compiling ts

CHANGELOG.md, src/app/components/tables/data-table/terra-data-table.component.html
=> fix (data-table): hide no results notice when request is pending

CHANGELOG.md, src/app/components/layouts/portlet/terra-portlet.component.html, src/app/components/layouts/portlet/terra-portlet.component.scss, src/app/components/layouts/portlet/terra-portlet.component.ts
=> Differentiate collapsible portlets from the background.

package-lock.json, package.json
=> fix (security vulnerability): update moment

src/app/models/terra-key-value-pair.interface.ts, src/app/models/terra-key-value.interface.ts
=> feature (models): key-value interfaces

src/app/components/tables/data-table/terra-data-table.component.ts
=> hotfix (data table): reset selectedRowlist when searched

CHANGELOG.md, src/app/components/forms/multi-check-box/data/terra-multi-check-box-value.interface.ts
=> feature (multi-checkbox): optional `selected` property

CHANGELOG.md, src/app/components/split-view/multi/terra-multi-split-view.component.ts
=> fix (split-view): get bounding client rect error

CHANGELOG.md, src/app/components/pager/terra-pager.component.scss
=> fix (terra-pager): adjusted width of current page input

src/app/components/layouts/tag/data/terra-tag.interface.ts, src/app/components/layouts/tag/terra-tag.component.html, src/app/components/layouts/tag/terra-tag.component.ts, src/app/components/layouts/taglist/terra-taglist.component.html
@zakpur @MFrank84 @garvins @pweyrich 
So in etwa sieht es aus für folgenden Code:
```html
<terra-taglist [inputTagList]="dummyTagList">
</terra-taglist>
```
```ts
this.dummyTagList = [
{
badge: 'tag1',
customClass: 'dummyClass1',
color: '#f0f00a',
isTaggable: true
},
{
badge: 'tag2',
customClass: 'dummyClass2',
color: '#0aa00a',
isTagged: true
},
{
badge: 'tag3',
customClass: 'dummyClass3',
color: '#a00a0a',
isTaggable: true
},
{
badge: 'tag4',
customClass: 'dummyClass4',
isTaggable: true
},
{
badge: 'tag5',
customClass: 'dummyClass5',
color: '#84ffe6',
isTagged: true
}
];
```
=> NEW terra-tag with own background color

src/app/components/file-browser/file-list/file-list.component.ts, src/app/components/file-browser/terra-file-browser.service.ts
=> FIX event handling

CHANGELOG.md
=> ADD changelog for file-chooser component

CHANGELOG.md, src/app/components/split-view/multi/terra-multi-split-view.component.scss, src/app/components/toolbar/base-toolbar/terra-base-toolbar.component.scss
=> fixed zIndex in toolbar

CHANGELOG.md, src/app/helpers/string.helper.ts
=> feature (string-helper): new helper for strings

CHANGELOG.md, src/app/components/forms/select-box/terra-select-box.component.ts
=> fix (select-box): issue when selectedValue is undefined

CHANGELOG.md, src/app/components/split-view/multi/terra-multi-split-view.component.ts
source changed to enable tab duplication with new routing
=> change source of component route

CHANGELOG.md, src/app/assets/themes/theme-dark-compact.scss, src/app/assets/themes/theme-dark-standard.scss, src/app/components/alert/terra-alert-panel.component.glob.scss, src/app/components/file-browser/file-list/file-list.component.html, src/app/components/file-browser/file-list/file-list.component.scss, src/app/components/file-browser/image-preview/image-preview.component.html, src/app/components/file-browser/image-preview/image-preview.component.scss, src/app/components/file-browser/terra-file-browser.component.scss, src/app/components/forms/input/color-picker/terra-color-picker.component.html, src/app/components/forms/input/color-picker/terra-color-picker.component.scss, src/app/components/forms/input/file-input/terra-file-input.component.scss, src/app/components/forms/input/terra-input.component.scss, src/app/components/forms/select-box/terra-select-box.component.scss, src/app/components/layouts/overlay/terra-overlay.component.scss, src/app/components/layouts/portlet/terra-portlet.component.scss, src/app/components/layouts/tag/terra-tag.component.scss, src/app/components/split-view/multi/terra-multi-split-view.component.html, src/app/components/split-view/multi/terra-multi-split-view.component.scss, src/app/components/split-view/terra-split-view.component.scss, src/app/components/tables/simple/terra-simple-table.component.scss, src/app/components/toolbar/base-toolbar/terra-base-toolbar.component.glob.scss, src/app/components/toolbar/base-toolbar/terra-base-toolbar.component.html, src/app/components/toolbar/base-toolbar/terra-base-toolbar.component.scss, src/app/components/toolbar/base-toolbar/terra-base-toolbar.component.ts, src/index.glob.scss
=> Team terra/act facelift/facelift chakra

src/app/components/split-view/multi/terra-multi-split-view.component.ts
=> fix (multi-split-view): undefined component route

CHANGELOG.md, src/app/components/forms/suggestion-box/terra-suggestion-box.component.ts
=> Fix (suggestion box): close on outside clicked

src/app/components/tables/simple/terra-simple-table.component.scss
=> FIX styles of fixed header directive

src/app/components/file-browser/file-list/file-list.component.scss, src/app/components/file-browser/model/s3-storage-object.interface.ts, src/app/components/file-browser/model/terra-storage-object.ts
=> FIX bugs in file list

src/app/components/tree/node-tree/data/terra-node-tree.config.ts, src/app/components/tree/node-tree/terra-node-tree.component.ts
=> fix (node tree): search

CHANGELOG.md, src/app/components/layouts/portlet/terra-portlet.component.html, src/app/components/layouts/portlet/terra-portlet.component.scss
=> Fixed dropdowns being cut off in collapsable portlets.

CHANGELOG.md, src/app/components/tables/data-table/context-menu/directive/terra-data-table-context-menu.directive.ts, src/app/components/tables/data-table/context-menu/terra-data-table-context-menu.component.html, src/app/components/tables/data-table/context-menu/terra-data-table-context-menu.component.ts
=> FIX (context menu) cannot be opened

CHANGELOG.md, src/app/components/buttons/button/data/terra-button.interface.ts, src/app/components/buttons/button/terra-button.component.ts, src/app/components/tables/data-table/terra-data-table.component.html
-add „isFlagged“ to button list in terra-data-table
@Neill83
=> -stop click event on terra-button

CHANGELOG.md, src/app/components/tables/data-table/terra-data-table.component.html, src/app/components/tables/data-table/terra-data-table.component.ts, src/app/components/tables/simple/terra-simple-table.component.html, src/app/components/tables/simple/terra-simple-table.component.ts
=> fix (simple table): cell text alignment

src/app/components/forms/dynamic-form/handler/terra-dynamic-form-functions.handler.ts, src/app/components/forms/dynamic-form/terra-dynamic-form.component.ts
=> Make debounce of change callback customizable

CHANGELOG.md, src/app/components/layouts/column-container/terra-two-columns-container.component.scss, src/app/components/layouts/column-container/terra-two-columns-container.component.ts
=> added mobile handling

CHANGELOG.md, src/app/components/forms/suggestion-box/terra-suggestion-box.component.ts
=> fix (suggestion-box): reset selected value if inputListBoxValues is empty

src/app/components/forms/form/model/terra-form-type-map.enum.ts
=> FIX terra-form legacy type map

CHANGELOG.md, src/app/components/editors/base-editor/terra-base-editor.component.html, src/app/components/editors/base-editor/terra-base-editor.component.ts, src/app/components/editors/code-editor/terra-code-editor.component.ts, src/app/components/forms/form/form-entry/terra-form-entry.component.ts, src/app/components/forms/form/model/terra-form-type-map.enum.ts
=> Implement ControlValueAccessor interface correctly

CHANGELOG.md, src/app/components/file-browser/file-list/file-list.component.ts
=> fixed file upload by select not working with firefox

src/app/components/forms/form/form-entry-list/terra-form-entry-list.component.html, src/app/components/forms/form/form-entry-list/terra-form-entry-list.component.ts
=> FIX tracking of list form entries

src/app/components/editors/code-editor/terra-code-editor.component.html, src/app/components/editors/code-editor/terra-code-editor.component.scss, src/app/components/editors/code-editor/terra-code-editor.component.ts
=> Check syntax of entered code and display parser errors

CHANGELOG.md, src/app/components/file-browser/config/file-browser-split.config.ts, src/app/components/file-browser/terra-file-browser.component.ts
=> fix (file browser): reset views on input service change

CHANGELOG.md, src/app/components/editors/note-editor/terra-note-editor.component.html
=> FIX changed ngModelCHange to onChangeCallback

src/app/components/file-browser/terra-file-browser.component.ts
=> fix (file-browser): endless loop because of nested split view

src/app/components/tree/node-tree/data/terra-node-tree.config.ts
=> Make currentSelectedNode visible for inherited classes

CHANGELOG.md, package.json, src/app/assets/lang/locale-de.json, src/app/assets/lang/locale-en.json, src/app/components/editors/code-editor/helper/html-linter-message.interface.ts, src/app/components/editors/code-editor/helper/html-linter-rule.enum.ts, src/app/components/editors/code-editor/helper/html-linter.helper.ts, src/app/components/editors/code-editor/terra-code-editor.component.ts
=> FIX use html linter to validate user input

package-lock.json, package.json
because of security vulnerabilities
can be tested with `npm run test`
there are two unit tests available which must be successful and a chrome window must be opened
=> updated karma to 3.0.0

CHANGELOG.md, src/app/components/tree/node-tree/data/terra-node-tree.config.ts
fixing a Nullpointer while changing the language in the drop down of the shop builder
=> Fixing a null pointer in the node tree

CHANGELOG.md, src/app/components/forms/suggestion-box/example/terra-suggestion-box.component.example.ts, src/app/components/forms/suggestion-box/terra-suggestion-box.component.ts
=> hotfix (suggestion-box): do not reset input text value when typing

src/app/components/tables/fixed-header/fixed-header.directive.ts, src/app/components/tree/node-tree/example/terra-node-tree.component.example.ts, src/app/service/terra-base.service.ts
=> Removed: underscores part 2

PULL_REQUEST_TEMPLATE.md
see https://blog.github.com/2016-02-17-issue-and-pull-request-templates/
Preview:
Documentation
Testing
=> feature: Pull Request template

CHANGELOG.md, src/app/components/tables/data-table/terra-data-table.component.ts
Documentation
Testing
Testing with beta7 and any view that includes a data table
=> hotfix (data table): rowlist initialisation

src/app/components/file-browser/model/terra-upload-item.ts, src/app/components/file-browser/model/terra-upload-queue.ts
=> FIX function call

src/app/components/layouts/info-box/terra-info-box.component.scss
=> modifications to info-box scss file

CHANGELOG.md, src/app/components/buttons/button/terra-button.component.scss
=> Fixed: Button group

CHANGELOG.md, src/app/assets/styles/icons.glob.scss, src/app/components/buttons/button/terra-button.component.scss
=> updated highlighted buttons to match functions groups

CHANGELOG.md, src/app/components/buttons/button-with-options/terra-button-with-options.component.ts, src/app/components/buttons/button/data/terra-button.interface.ts
=> added deprecated to button interface

tsconfig.json
=> avoid creation of .d.ts files

CHANGELOG.md, src/app/components/tables/data-table/terra-data-table.component.html
=> fix (data-table): pass click event to a button's `clickFunction`

src/app/components/stopwatch/example/terra-stopwatch.component.example.html, src/app/components/stopwatch/terra-stopwatch.component.html
=> fix stopwatch

tsconfig.json
=> fix (build): exclude *.d.ts files from compilation

CHANGELOG.md, src/app/components/tables/data-table/cell/terra-data-table-text.interface.ts, src/app/components/tables/data-table/terra-data-table.component.html, src/app/components/tables/data-table/terra-data-table.component.ts
The TODOs will be covered in another pull request.
Documentation
Testing
=> hotfix (data-table): cell content format

CHANGELOG.md, package-lock.json, package.json, src/app/components/forms/input/date-picker/terra-date-picker.component.ts
=> hotfix (date-picker): date string format

src/app/components/tables/simple/terra-simple-table.component.ts
=> improvement

src/app/components/forms/input/color-picker/terra-color-picker.component.html, src/app/components/forms/input/date-picker/terra-date-picker.component.html, src/app/components/forms/input/double-input/terra-double-input.component.html, src/app/components/forms/input/file-input/terra-file-input.component.html, src/app/components/forms/input/number-input/terra-number-input.component.html, src/app/components/forms/input/text-input/terra-text-input.component.html, src/app/components/forms/select-box/terra-select-box.component.html
=> added container to html for tooltip

PULL_REQUEST_TEMPLATE.md
work-around until jenkins check unit tests
=> updated pr template with unit test success check

src/app/components/tables/data-table/terra-data-table.component.html, src/app/components/tables/data-table/terra-data-table.component.scss, src/app/components/tables/data-table/terra-data-table.component.ts
=> feature (data-table): add icon that indicates whether a column is sortable

CHANGELOG.md, src/app/components/tree/node-tree/data/terra-node-tree.config.ts, src/app/components/tree/node-tree/data/terra-node.interface.ts, src/app/components/tree/node-tree/node/terra-node.component.html, src/app/components/tree/node-tree/node/terra-node.component.ts
=> node click fix

CHANGELOG.md, src/app/helpers/regex/terra-regex.ts
=> (terra-regex): remove getters - instead grant public access to the members

src/app/components/forms/suggestion-box/terra-suggestion-box.component.spec.ts
=> add TerraLabelTooltipDirective to fix tests

src/app/components/forms/input/number-input/terra-number-input.component.html, src/app/components/forms/input/number-input/terra-number-input.component.spec.ts
=> number input tests

src/app/components/forms/input/double-input/terra-double-input.component.html, src/app/components/forms/input/double-input/terra-double-input.component.spec.ts, src/app/components/forms/input/double-input/terra-double-input.component.ts
=> double input unit test

src/app/components/forms/input/text-area-input/terra-text-area-input.component.html, src/app/components/forms/input/text-area-input/terra-text-area-input.component.spec.ts, src/app/components/forms/input/text-area-input/terra-text-area-input.component.ts
=> text area unit tests

src/app/helpers/tests/number.helper.spec.ts
=> Unit test/number helper

src/app/components/forms/input/file-input/terra-file-input.component.html, src/app/components/forms/input/file-input/terra-file-input.component.spec.ts, src/app/components/forms/input/file-input/terra-file-input.component.ts, src/app/testing/file-input/file-data.ts, src/app/testing/file-input/terra-frontend-storage-service-stub.ts
=> Unit test/terra input file input

CHANGELOG.md, src/app/components/tables/simple/example/terra-simple-table.component.example.html, src/app/components/tables/simple/example/terra-table-simple.component.example.ts, src/app/components/tables/simple/terra-simple-table.component.ts
=> fix (simple-table): notifications via outputSelectedRowsChange

CHANGELOG.md, src/app/components/tables/data-table/terra-data-table.component.html, src/app/components/tables/data-table/terra-data-table.component.scss
=> fix (data-table): styles for href cells

src/app/components/forms/suggestion-box/terra-suggestion-box.component.spec.ts
=> fix (suggestion-box): unit test

CHANGELOG.md, src/app/components/tables/data-table/terra-data-table-base.service.ts, src/app/components/tables/data-table/terra-data-table.component.html, src/app/components/tables/data-table/terra-data-table.component.ts
=> fix (data-table): update rowlist

src/app/helpers/tests/string.helper.spec.ts
=> unit test for the string helper

src/app/components/layouts/card/terra-card.component.html, src/app/components/layouts/card/terra-card.component.spec.ts, src/app/components/layouts/card/terra-card.component.ts
=> Unit test (card): NEW

src/app/components/layouts/portlet/terra-portlet.component.html, src/app/components/layouts/portlet/terra-portlet.component.scss, src/app/components/layouts/portlet/terra-portlet.component.spec.ts, src/app/components/layouts/portlet/terra-portlet.component.ts
=> Unit test/portlet

src/app/components/layouts/column-container/three-columns/terra-three-columns-container.component.spec.ts
=> unit-test (three-column-container): refactored tests

CHANGELOG.md, src/app/components/layouts/tag/example/terra-tag.component.example.html, src/app/components/layouts/tag/terra-tag.component.ts
=> (tag): add deprecation warning to `inputBadge`

src/app/components/indicator/terra-indicator.component.spec.ts, src/app/components/info/terra-info.component.spec.ts, src/app/components/layouts/card/terra-card.component.spec.ts, src/app/components/layouts/info-box/terra-info-box.component.spec.ts
=> Unit test: change descriptions

CHANGELOG.md, src/app/components/tables/data-table/example/terra-data-table.component.example.html, src/app/components/tables/data-table/example/terra-data-table.component.example.ts, src/app/components/tables/data-table/example/terra-data-table.service.example.ts, src/app/components/tables/data-table/terra-data-table-base.service.ts, src/app/components/tables/data-table/terra-data-table.component.ts
=> fix (data table): reset sorting

CHANGELOG.md, src/app/components/tree/node-tree/data/terra-node-tree.config.ts
=> fixed the deletion of a node on first level

CHANGELOG.md, src/app/components/layouts/column-container/three-columns/terra-three-columns-container.component.scss, src/app/components/layouts/column-container/two-columns/terra-two-columns-container.component.scss
=> fix for 2 and 3 column container in firefox

CHANGELOG.md, src/app/components/forms/slider/example/terra-slider.component.example.html, src/app/components/forms/slider/example/terra-slider.component.example.ts, src/app/components/forms/slider/terra-slider.component.html, src/app/components/forms/slider/terra-slider.component.spec.ts, src/app/components/forms/slider/terra-slider.component.ts
=> feature (terra slider): implement ControlValueAccessor interface to be able to use ngModel

src/app/components/example-collection.ts, src/app/components/forms/terra-forms.example.html, src/app/components/forms/terra-forms.example.ts
=> feature (forms): example

CHANGELOG.md, src/app/components/forms/select-box/terra-select-box.component.html, src/app/components/forms/select-box/terra-select-box.component.scss, src/app/components/forms/select-box/terra-select-box.component.ts
=> focusable select box

src/app/components/forms/terra-forms.example.ts
=> FIX (terra-forms-example): loading in terra

src/app/components/forms/input/radio/terra-radio-input.component.html, src/app/components/forms/input/radio/terra-radio-input.component.scss, src/app/components/forms/input/radio/terra-radio-input.component.spec.ts, src/app/components/forms/terra-forms.example.html
=> feature (radio-input): adjust styling

CHANGELOG.md, src/app/components/forms/checkbox/terra-checkbox.component.scss
=> removed outline

src/app/components/forms/select-box/terra-select-box.component.ts
=> added preventDefault

src/app/components/forms/input/radio/terra-radio-group.component.ts, src/app/components/forms/input/radio/terra-radio-input.component.scss
=> fix (radio-input): height of label

src/app/components/forms/select-box/terra-select-box.component.ts
=> fixed preventDefault

CHANGELOG.md, src/app/components/layouts/portlet/example/terra-portlet.component.example.html, src/app/components/layouts/portlet/terra-portlet.component.html, src/app/components/layouts/portlet/terra-portlet.component.scss, src/app/components/layouts/portlet/terra-portlet.component.spec.ts, src/app/components/layouts/portlet/terra-portlet.component.ts
=> ADD disabled option for portlets

CHANGELOG.md, src/app/components/dynamic-module-loader/data/terra-split-view-component.interface.ts
=> feature(TerraSplitViewComponentInterface): mark as deprecated

CHANGELOG.md, src/app/components/forms/form/model/terra-form-type-map.enum.ts
=> fix(terra-form): Added inputMapping to distinguish required inputs

src/app/assets/styles/icons.glob.scss, src/index.glob.scss
=> FIX order of scss files loading

config/webpack.test.js
=> fix(webpack): config for tests

CHANGELOG.md, src/app/components/forms/form/form-entry/terra-form-entry.component.ts
=> fix(terra-form-entry): initialization with defaultValue

CHANGELOG.md, src/app/components/forms/form/helper/terra-form-field.helper.ts, src/app/components/forms/form/model/form-type-map.ts, src/app/components/forms/form/model/terra-form-type-map.enum.ts
=> feature(terra-form): add support for slider

CHANGELOG.md, src/app/components/breadcrumbs/service/terra-breadcrumbs.service.ts, src/app/components/breadcrumbs/terra-breadcrumb-container.ts, src/app/components/breadcrumbs/terra-breadcrumb.ts, src/app/components/breadcrumbs/terra-breadcrumbs.component.html
=> fix(breadcrumb container): hide if no data is given

CHANGELOG.md, src/app/components/forms/checkbox-group/checkbox-group.component.html, src/app/components/forms/checkbox-group/checkbox-group.component.spec.ts, src/app/components/forms/checkbox-group/checkbox-group.component.ts, src/app/components/forms/multi-check-box/terra-multi-check-box.component.ts
=> fix(checkbox-group): null value handling

CHANGELOG.md, src/app/components/info/terra-info.component.html
=> fix(terra-info): changed container of tooltip

CHANGELOG.md, src/app/components/buttons/button/terra-button.component.ts, src/app/components/forms/checkbox/example/terra-checkbox.component.example.html, src/app/components/forms/checkbox/terra-checkbox.component.html, src/app/components/forms/checkbox/terra-checkbox.component.scss, src/app/components/forms/checkbox/terra-checkbox.component.ts
=> added tooltip for checkbox

src/app/components/forms/checkbox/example/terra-checkbox.component.example.html, src/app/components/forms/checkbox/terra-checkbox.component.html, src/app/components/forms/checkbox/terra-checkbox.component.ts
=> fix(terra-checkbox): refactor naming

src/app/components/forms/checkbox/terra-checkbox.component.html, src/app/components/forms/checkbox/terra-checkbox.component.ts, src/app/components/tables/data-table/table-row/table-row.component.spec.ts
=> fix(terra-checkbox): refactor tooltip

package-lock.json, package.json
=> fix (security vulnerability): karma

src/app/components/buttons/button/example/terra-button.component.example.ts, src/app/components/data-picker/nested-data-picker/example/service/terra-nested-data-picker.service.example.ts, src/app/components/editors/code-editor/terra-code-editor.component.ts, src/app/components/forms/checkbox-group/checkbox-group.component.spec.ts, src/app/components/forms/checkbox/terra-checkbox.component.ts, src/app/components/forms/dynamic-form/data/terra-form-field-multi-check-box.ts, src/app/components/forms/form/form-entry/terra-form-entry.component.ts, src/app/components/forms/form/helper/terra-form-field.helper.ts, src/app/components/forms/form/model/terra-form-scope.data.ts, src/app/components/forms/form/model/terra-form-type-map.enum.ts, src/app/components/forms/input/text-area-input/terra-text-area-input.component.spec.ts, src/app/components/info/example/terra-info.component.example.ts, src/app/components/info/terra-info.component.spec.ts, src/app/components/layouts/info-box/example/terra-info-box.component.example.ts, src/app/components/layouts/info-box/terra-info-box.component.spec.ts, src/app/components/layouts/overlay/terra-overlay.component.ts, src/app/components/pager/data/terra-pager-default-paging-sizes.ts, src/app/components/split-view/multi/injectables/terra-multi-split-view-breadcrumbs.service.ts, src/app/service/service-collection.ts, src/app/testing/mock-buttons.ts
=> (fix): path of imports

CHANGELOG.md, src/index.ts
… to be able to import it from `@plentymarkets/terra-components`
Documentation
Testing
=> fix(AlertService): add it to index.ts 

CHANGELOG.md, src/app/components/forms/input/date-picker/terra-date-picker.component.glob.scss, src/app/components/forms/input/terra-input.component.scss, src/app/components/forms/multi-check-box/terra-multi-check-box.component.scss, src/app/components/forms/select-box/terra-select-box.component.scss, src/app/components/tables/data-table/custom-data-table.scss, src/app/components/tables/data-table/example/data-table-template.component.example.html
=> [Feature] styles for components that are inserted in data table 

CHANGELOG.md, src/app/components/breadcrumbs/service/terra-breadcrumbs.service.ts, src/app/components/breadcrumbs/terra-breadcrumbs.component.ts, src/app/helpers/activated-route.helper.ts
=> fix(breadcrumbs): initialPath evaluation for routes with empty path

CHANGELOG.md, src/app/styles/themes/theme-dark.scss, src/app/styles/themes/theme-light.scss
=> [FIX] tooltip color for light theme for better contrast

CHANGELOG.md, src/app/components/data-picker/category-picker/terra-category-picker.component.ts
- added webstore id to category picker
Documentation
Testing
=> feature (terra-category-picker): Added an input to the category-picker to pass the webstore id

CHANGELOG.md, src/app/components/forms/select-box/terra-select-box.component.spec.ts, src/app/components/forms/select-box/terra-select-box.component.ts
=> fix(select-box): add fallback handling

CHANGELOG.md, src/app/components/forms/form/helper/terra-form.helper.ts, src/app/components/forms/form/terra-form.component.ts
=> Set empty array if value of list entries are not defined

CHANGELOG.md, src/app/components/forms/input/radio/radio-group.component.spec.ts, src/app/components/forms/input/radio/radio-group.component.ts, src/app/terra-components.component.html
=> fix (tc-radio-group): generating name if not set

CHANGELOG.md, src/app/components/forms/form/form-container/terra-form-container.component.ts
=> fix (form): disable hidden form field validation

CHANGELOG.md, src/app/components/forms/form/helper/terra-form.helper.ts
=> fix(form): toggle state validation

CHANGELOG.md, src/app/components/forms/multi-check-box/terra-multi-check-box.component.scss
=> feature (mutli-check-box): Added invalid state indication

CHANGELOG.md, src/app/components/layouts/card/terra-card.component.scss
=> add variable support

CHANGELOG.md, src/app/components/forms/input/radio/radio-group.component.spec.ts, src/app/components/forms/input/radio/radio-group.component.ts
=> fix(radio-group): do not execute change callback on #writeValue

CHANGELOG.md, src/app/components/forms/form/helper/terra-form-field.helper.spec.ts, src/app/components/forms/form/helper/terra-form-field.helper.ts, src/app/components/forms/form/terra-form.component.ts
=> fix(terra-form): fix instance clash with objects and arrays as default value

CHANGELOG.md, package-lock.json, package.json
=> fix(general): reduce interactjs version

CHANGELOG.md, src/app/components/layouts/card/terra-card.component.scss
=> feature(card:) new css variable to be able to redefine the footer's min height

CHANGELOG.md, src/app/components/buttons/button/terra-button.component.scss
=> added variable for margin & display

src/app/components/tables/data-table/example/data-table-template.component.example.html, src/app/components/tables/data-table/example/data-table-template.component.example.ts, src/app/components/tables/data-table/example/terra-data-table.component.example.ts
=> [FIX] Updated editable table example

CHANGELOG.md, src/app/components/forms/form/form-container/terra-form-container.component.scss
=> remove flex style

CHANGELOG.md, package-lock.json, package.json, src/app/components/example-collection.ts, src/app/components/forms/form/example/form-fields.ts, src/app/components/forms/form/example/terra-form.component.example.html, src/app/components/forms/form/example/terra-form.component.example.ts, src/app/components/forms/form/helper/terra-form-field.helper.spec.ts, src/app/components/forms/form/helper/terra-form-field.helper.ts, src/app/components/forms/form/helper/terra-form.helper.ts, src/app/components/forms/form/terra-form.component.html, src/app/components/forms/form/terra-form.component.ts
=> fix(form): parse default values

src/app/components/forms/form/helper/terra-form.helper.spec.ts, src/app/components/forms/form/helper/terra-form.helper.ts
=> feature (terra-form): created unit tests for form helper

CHANGELOG.md, src/app/http-interceptors/index.ts, src/app/http-interceptors/loading.interceptor.spec.ts, src/app/http-interceptors/loading.interceptor.ts
=> feature(http): loading interceptor

CHANGELOG.md, src/app/http-interceptors/error.interceptor.ts
before:
after:
Documentation
Testing
=> fix(http): make error-interceptor log the complete error response

CHANGELOG.md, config/webpack.common.js, src/app/components/alert/terra-alert-panel.component.glob.scss, src/app/components/buttons/button/terra-button.component.html, src/app/components/buttons/button/terra-button.component.scss, src/app/components/buttons/toggle/example/terra-toggle.component.example.html, src/app/components/buttons/toggle/terra-toggle.component.html, src/app/components/file-browser/file-list/file-list.component.html, src/app/components/forms/dynamic-form/terra-dynamic-form.component.ts, src/app/components/forms/input/terra-input.component.glob.scss, src/app/components/forms/multi-check-box/terra-multi-check-box.component.scss, src/app/components/layouts/card/terra-card.component.scss, src/app/components/layouts/column-container/three-columns/terra-three-columns-container.component.spec.ts, src/app/components/layouts/column-container/three-columns/terra-three-columns-container.component.ts, src/app/components/layouts/column-container/two-columns/terra-two-columns-container.component.spec.ts, src/app/components/layouts/info-box/terra-info-box.component.html, src/app/components/layouts/overlay/terra-overlay.component.html, src/app/components/layouts/overlay/terra-overlay.component.scss, src/app/components/layouts/overlay/terra-overlay.component.spec.ts, src/app/components/layouts/tag/terra-tag.component.scss, src/app/components/note/terra-note.component.html, src/app/components/split-view/multi/terra-multi-split-view.component.glob.scss, src/app/components/tables/simple/terra-simple-table.component.html, src/app/components/toolbar/base-toolbar/terra-base-toolbar.component.glob.scss, src/app/components/toolbar/base-toolbar/terra-base-toolbar.component.scss, src/app/helpers/two-column.helper.ts, src/app/styles/styles.scss
=> fix: revert bootstrap update

CHANGELOG.md, src/app/components/data-picker/category-picker/terra-category-picker.component.ts, src/app/components/forms/checkbox/terra-checkbox.component.ts
=> feature (Categorypicker & Checkbox):allow to accept null values

config/webpack.common.js, config/webpack.dev.js
=> fix assets in terra-components

CHANGELOG.md, src/app/components/interactables/draggable.directive.ts
=> fix(tslint/draggable.directive): Allow terraDraggable input to be renamed

CHANGELOG.md, package-lock.json, package.json, src/app/components/editors/code-editor/helper/html-linter.helper.ts
**note** hier noch antworten https://forum.plentymarkets.com/t/shopbuilder-html-widget-code-wird-nicht-gespeichert-und-widget-wird-nicht-aktualisiert/546659
Documentation
Testing
=> CHANGE html-linter.helper.ts - fix import of htmlhint

CHANGELOG.md, src/lib/components/forms/checkbox/terra-checkbox.component.scss, src/lib/components/forms/input/radio/radio-input.component.scss, src/lib/components/forms/radio-button/terra-radio-button.component.scss
=> fixed missing checkbox paddings

PULL_REQUEST_TEMPLATE.md
=> DoD: add conditions for criteria

src/lib/components/tables/data-table/context-menu/terra-data-table-context-menu.component.ts
=> feature (data-table/context-menu): append to body only if shown, remove it from body when hidden

CHANGELOG.md, src/lib/styles/themes/theme-core.scss
=> fix (terra-core.scss): remove border radius to improve performance

CHANGELOG.md, config/webpack.common.js, src/lib/components/alert/terra-alert-panel.component.ts, src/lib/components/editors/base-editor/terra-base-editor.component.glob.scss, src/lib/components/editors/base-editor/terra-base-editor.component.scss, src/lib/components/editors/base-editor/terra-base-editor.component.ts, src/lib/components/editors/code-editor/terra-code-editor.component.ts, src/lib/components/editors/note-editor/terra-note-editor.component.ts, src/lib/components/file-browser/terra-file-browser.component.ts, src/lib/components/forms/input/date-picker/terra-date-picker.component.ts, src/lib/components/forms/input/text-input/terra-text-input.component.ts, src/lib/components/split-view/multi/terra-multi-split-view.component.ts, src/lib/components/toolbar/base-toolbar/terra-base-toolbar.component.ts, src/lib/styles/fonts/plentysans.scss, src/lib/styles/styles.scss
=> fix glob style imports

src/lib/components/component-collection.ts
=> fix(component-collection): duplicate export category picker

CHANGELOG.md, src/lib/helpers/path.helper.ts, src/lib/helpers/tests/path.helper.spec.ts
@plentymarkets/ceres-io 
Documentation
Testing
=> Transform file extensions to lowercase for easier comparisons

CHANGELOG.md, src/lib/components/forms/checkbox-group/example/checkbox-group.component.example.ts, src/lib/components/forms/checkbox/terra-checkbox.component.ts, src/lib/components/forms/multi-check-box/terra-multi-check-box.component.html, src/lib/components/forms/multi-check-box/terra-multi-check-box.component.ts
=> fix/feature(checkbox/multi-checkbox): indeterminate state on checkboxgroup

src/lib/components/editors/ck-editor/example/ck-editor-directive-example.component.html, src/lib/components/editors/ck-editor/example/ck-editor-directive-example.component.ts
=> example(CKEditor): update example with new save logic

CHANGELOG.md, src/lib/components/alert/terra-alert-panel.component.glob.scss, src/lib/styles/themes/theme-core.scss
@plentymarkets/ceres-io 
Documentation
Testing
=> Fix alert zindex while overlay is active

CHANGELOG.md, src/lib/styles/themes/theme-core.scss
=> removed all css transitions

CHANGELOG.md, src/lib/components/split-view/multi/terra-multi-split-view.component.html, src/lib/components/split-view/multi/terra-multi-split-view.component.scss
=> fix (multi-split-view): fixed breadcrumb styles

src/lib/components/buttons/button/terra-button.component.scss
=> fix (terra-node): focus style

src/lib/components/tree/node-tree/node/terra-node.component.html, src/lib/components/tree/node-tree/node/terra-node.component.ts
=> fix (tree-node): add tooltip to node again

config/webpack.common.js, package-lock.json, package.json
=> added circular-dependency-plugin

CHANGELOG.md, src/lib/styles/themes/theme-core.scss, src/lib/styles/themes/theme-dark.scss, src/lib/styles/themes/theme-light.scss
=> feature(themes): added variables for the global search

CHANGELOG.md, src/lib/components/buttons/toggle/terra-toggle.component.html
=> fix(toggle button) tooltip

.travis.yml
=> fix (TravisCI): change installation of chrome

CHANGELOG.md, src/lib/components/filter/filter.component.spec.ts, src/lib/components/forms/checkbox-group/checkbox-group.component.spec.ts, src/lib/components/forms/checkbox/terra-checkbox.component.spec.ts, src/lib/components/forms/input/color-picker/terra-color-picker.component.spec.ts, src/lib/components/forms/input/double-input/terra-double-input.component.spec.ts, src/lib/components/forms/input/file-input/terra-file-input.component.spec.ts, src/lib/components/forms/input/number-input/terra-number-input.component.spec.ts, src/lib/components/forms/input/text-area-input/terra-text-area-input.component.spec.ts, src/lib/components/forms/input/text-input/terra-text-input.component.spec.ts, src/lib/components/forms/multi-check-box/terra-multi-check-box.component.spec.ts, src/lib/components/forms/select-box/terra-select-box.component.spec.ts, src/lib/components/forms/suggestion-box/terra-suggestion-box.component.spec.ts, src/lib/components/info/terra-info.component.spec.ts, src/lib/components/layouts/overlay/terra-overlay.component.spec.ts, src/lib/components/layouts/portlet/terra-portlet.component.spec.ts, src/lib/components/stopwatch/terra-stopwatch.component.spec.ts, src/lib/components/tables/data-table/table-row/table-row.component.spec.ts, src/lib/components/tables/data-table/terra-data-table.component.spec.ts, src/lib/components/tables/group-function/terra-group-function.component.spec.ts, src/lib/components/tooltip/tooltip.directive.spec.ts, src/lib/components/tooltip/tooltip.directive.ts
=> fix (tcTooltip): hide tooltip when routing

src/lib/styles/material/_select.scss
@Neill83 
Testing
----
Documentation
Testing
=> fix: material selectbox won't show selected value as bold text

CHANGELOG.md
=> added changelog entry

.gitignore
=> remove lintRules from gitignore

CHANGELOG.md, src/lib/components/forms/input/radio/radio-group.component.html, src/lib/components/forms/input/radio/radio-group.component.scss, src/lib/components/forms/input/radio/radio-group.component.spec.ts
Testing
----
Documentation
Testing
=> fix (radio-group legend): font-size and not displaying when not existing

gulp.config.js, gulpfile.js
=> copy floatThead to dist folder

src/app/app.module.ts, src/app/showcase/showcase.component.ts, src/app/translation/l10n.config.ts
Testing
----
Documentation
Testing
=> feature(dev-app): aot compilation

package.json
=> feature(ci): also build the dev-app

package.json
... since it is already required by tippy
Testing
----
Documentation
Testing
=> feature(dependencies): remove explicit dependency to popper 

src/lib/components/alert/terra-alert-panel.component.glob.scss
=> fix (alert-panel): new top value

CHANGELOG.md, src/lib/components/pager/terra-pager.component.scss, src/lib/components/tables/data-table/terra-data-table.component.scss
=> changed variables in pager

package-lock.json, src/lib/components/forms/form/helper/terra-form-field.helper.ts, src/lib/helpers/object.helper.ts
Testing
----
Documentation
Testing
=> fix(build): caused by cloneDeep

CHANGELOG.md, src/lib/components/forms/input/date-picker/terra-date-picker.component.html, src/lib/components/forms/input/double-input/terra-double-input.component.html, src/lib/components/forms/input/file-input/terra-file-input.component.html, src/lib/components/forms/input/number-input/terra-number-input.component.html, src/lib/components/forms/input/text-area-input/terra-text-area-input.component.html, src/lib/components/forms/input/text-input/terra-text-input.component.html
=> fix (inputs): set tabindex to -1 to avoid tab focus on labels

CHANGELOG.md, src/lib/components/buttons/button-with-options/terra-button-with-options.component.html
Testing
----
Documentation
Testing
=> FIX isHidden for terra button with options

CHANGELOG.md, src/lib/components/editors/base-editor/terra-base-editor.component.glob.scss
- removed unnecessary quill style import
Testing
----
Documentation
=> fix (terra-base-editor): quill import

CHANGELOG.md
Added missing changelog for https://github.com/plentymarkets/terra-components/pull/1061
Documentation
=> feature(terra-portlet):added missing changelog

CHANGELOG.md, src/lib/components/tables/data-table/float-thead/float-thead.directive.ts, src/lib/components/tables/data-table/terra-data-table.component.ts
… of the DataTableComponent
Testing
----
Documentation
=> feature(data-table): deprecated FloatTheadDirective and the input `isSticky`

CHANGELOG.md, src/lib/helpers/fileType.helper.ts
Testing
----
Documentation
Testing
=> feature (file-browser): add one more type

src/lib/components/tables/data-table/terra-data-table.component.html
=> fix(data-table): missing classes

src/lib/components/file-browser/model/terra-upload-item.ts
=> fix(upload-item): access to private event callback lists

src/lib/components/forms/input/date-picker/terra-date-picker.component.html
=> fix(date-picker): placeholder

CHANGELOG.md, src/lib/styles/material/_tab.scss, src/lib/styles/styles.scss, src/lib/styles/themes/theme-core.scss, src/lib/styles/themes/theme-light.scss
Testing
----
Documentation
Testing
=> scss for tabs

CHANGELOG.md, src/lib/components/info/terra-info.component.scss, src/lib/components/layouts/info-box/terra-info-box.component.scss, src/lib/components/layouts/portlet/terra-portlet.component.scss, src/lib/components/pager/terra-pager.component.scss, src/lib/components/tables/data-table/example/terra-data-table.component.example.html, src/lib/components/tables/data-table/terra-data-table.component.scss
=> Infobox and Table in Portlet

CHANGELOG.md, src/lib/components/info/terra-info.component.scss, src/lib/components/layouts/info-box/terra-info-box.component.scss, src/lib/components/layouts/portlet/terra-portlet.component.scss, src/lib/components/pager/terra-pager.component.scss, src/lib/components/tables/data-table/example/terra-data-table.component.example.html, src/lib/components/tables/data-table/terra-data-table.component.scss
=> Merge v4 to v5

CHANGELOG.md, src/lib/styles/themes/theme-core.scss
=> Team terra/terra design/space enhancement

angular.json
=> add missing angular material theme

src/lib/styles/material/_tab.scss
=> remove border bottom

CHANGELOG.md, src/lib/components/forms/input/date-picker/terra-date-picker.component.ts
=> deprecate date-picker

.travis.yml
=> feature(ci): add test build to travis config

src/lib/components/forms/form/form-container/terra-form-container.component.html, src/lib/components/forms/form/form-container/terra-form-container.component.scss, src/lib/components/forms/form/form-container/terra-form-container.component.ts
* add appropriate classes to the form-entry
* add input `horizontal` to the TerraFormContainerComponent to indicate whether it is a horizontal container or not
=> * calculate width of a form entry in a horizontal container

src/lib/components/forms/form/form-container/terra-form-container.component.html, src/lib/components/forms/form/form-container/terra-form-container.component.scss, src/lib/components/forms/form/form-container/terra-form-container.component.ts
Reverts plentymarkets/terra-components#1092
=> Revert "* calculate width of a form entry in a horizontal container"

src/lib/components/forms/form/form-container/terra-form-container.component.spec.ts
=> test for default width

src/lib/components/forms/form/form-container/terra-form-container.component.spec.ts
=> feature(form): unit test for a specific form element width

src/lib/components/forms/form/form-container/terra-form-container.component.html, src/lib/components/forms/form/form-container/terra-form-container.component.spec.ts, src/lib/components/forms/form/form-container/terra-form-container.component.ts
=> feature(form): simplify equal distribution of the cols in a horizontal container

src/lib/components/forms/form/form-container/terra-form-container.component.html, src/lib/components/forms/form/form-container/terra-form-container.component.spec.ts, src/lib/components/forms/form/terra-form.component.html, src/lib/components/forms/form/terra-form.component.scss, src/lib/components/forms/form/terra-form.component.spec.ts, src/lib/components/forms/form/terra-form.component.ts
=> feature (terra-form): container for form elements

CHANGELOG.md, src/lib/styles/styles.scss
=> fix(styles): adjust row margins when nesting the grid and adjust padding for the "col" as well

src/lib/styles/styles.scss
=> fixed selector for bootstrap columns

CHANGELOG.md, src/lib/components/buttons/button-with-options/terra-button-with-options.component.ts
=> Emit toggle event

src/lib/public-api.ts
Testing
----
Documentation
Testing
=> fix: add FilterComponent to public api

CHANGELOG.md, src/lib/styles/material/_tab.scss
=> min_width for material tabs

CHANGELOG.md, src/lib/http-interceptors/index.ts
=> fix(http-interceptors): add dependencies to the providers to make them actually work

CHANGELOG.md, src/lib/components/file-browser/terra-base-storage.interface.ts, src/lib/components/file-browser/terra-frontend-storage.service.ts
=> feature(file-browser): use HttpClient instead of TerraBaseService

browserslist, src/lib/tsconfig.spec.json, src/tsconfig.app.json, tsconfig.json
Testing
----
Documentation
Testing
=> update latest ts config

package-lock.json, package.json
Reverts plentymarkets/terra-components#1126
=> Revert "feature(app): switch back to the native node sass version "

CHANGELOG.md, src/lib/components/editors/syntax-editor/terra-syntax-editor.component.ts
=> feature(syntax editor): deprecate

CHANGELOG.md, src/lib/components/file-browser/terra-frontend-storage.service.ts
=> fix (TerraFrontendStorageService): false params in delete method 

CHANGELOG.md, src/lib/styles/material/_tab.scss
=> [FIX] display:none state of mat-ink-bar in mat-tabs

package.json, src/lib/package.json
=> update version to 5.0.0-rc.0

CHANGELOG.md, src/lib/utils/http-param-encoder.ts, src/lib/utils/http-params.ts
=> fix(http-params): create http params with a custom encoder

CHANGELOG.md, package-lock.json, package.json, src/lib/package.json
=> feature(deps): remove flatted

package-lock.json, package.json
=> feature(deps): update yargs

package-lock.json, package.json
=> feature(deps): update semver

CHANGELOG.md, src/lib/components/forms/checkbox-group/checkbox-group.component.spec.ts, src/lib/components/forms/checkbox-group/checkbox-group.component.ts
Testing
----
Documentation
Testing
=> Maintain checkbox group sorting when selecting/deselecting checkboxes

CHANGELOG.md, package-lock.json
=> fix (security vulnerability): acorn

CHANGELOG.md, src/lib/components/layouts/column-container/three-columns/terra-three-columns-container.component.scss, src/lib/components/layouts/column-container/two-columns/terra-two-columns-container.component.scss
Testing
Responsiveness
Responsiveness
----
Documentation
=> fix(terra-two-columns, terra-three-columns):updated col paddings

package-lock.json, package.json
=> feature(deps): update @angular/cli

CHANGELOG.md, src/lib/components/interactables/draggable.directive.ts, src/lib/components/interactables/dropzone.directive.ts, src/lib/components/interactables/resizable.directive.ts
=> Feature(interactables): Deprecate directives

CHANGELOG.md, src/lib/components/stopwatch/terra-stopwatch.component.spec.ts, src/lib/components/stopwatch/terra-stopwatch.component.ts
Testing
----
Documentation
Testing
=> feature(stopwatch): start timer once

package-lock.json
=> fix(security vulnerabilities): update packages

package.json
=> feature: npm ci

CHANGELOG.md, src/lib/components/alert/terra-alert-panel.component.html, src/lib/components/alert/terra-alert-panel.component.ts, src/lib/components/alert/terra-alert.component.ts, src/lib/terra-components.module.ts
=> feature(alert): use bootstrap directly instead of ngx-bootstrap

CHANGELOG.md, src/lib/components/layouts/portlet/terra-portlet.component.scss
Testing
Responsiveness
Responsiveness
----
Documentation
=> FIX (portlet): overflow

README.md
=> update link and wording in README.md

src/lib/service/table/table-data-source.ts, src/lib/service/table/table-paging-data-source.ts, src/lib/service/table/table-sorting-data-source.ts
Testing
Responsiveness
Responsiveness
----
Documentation
Testing
=> little refactoring

CHANGELOG.md, src/lib/components/dynamic-component-loader/terra-dynamic-component-loader.component.ts
=> feature(dynamic-component-loader): deprecation

CHANGELOG.md, src/lib/components/buttons/toggle/terra-toggle.component.ts
=> feature(toggle): deprecation

CHANGELOG.md, src/lib/components/data-picker/category-picker/terra-category-picker.component.ts
=> feature(category-picker): removed provider for TerraNodeTreeConfig

PULL_REQUEST_TEMPLATE.md
Testing
Responsiveness
Responsiveness
----
Documentation
Testing
=> feature(PULL_REQUEST_TEMPLATE): update for deprecated APIs and features

src/lib/service/table/has-paginator.interface.ts, src/lib/service/table/table-data-source.ts, src/lib/service/table/table-paging-data-source.ts, src/lib/service/table/table-paging-sorting-data-source.ts
Testing
Responsiveness
Responsiveness
----
Documentation
Testing
=> feature(CustomDataSource): parse data from TerraPagerInterface

CHANGELOG.md, src/lib/styles/material/_table.scss, src/lib/styles/styles.scss, src/lib/styles/themes/theme-core.scss
Testing
Responsiveness
Responsiveness
----
Documentation
=> feature (mat-table): added styles

CHANGELOG.md, src/lib/components/layouts/overlay/terra-overlay.component.ts
=> feature(overlay): deprecation

CHANGELOG.md, src/lib/components/forms/input/terra-input.component.ts
=> feature(terra-input): deprecation

src/lib/components/filter/filter.component.spec.ts, src/lib/components/forms/checkbox-group/checkbox-group.component.spec.ts, src/lib/components/forms/input/text-input/terra-text-input.component.spec.ts, src/lib/components/forms/multi-check-box/terra-multi-check-box.component.spec.ts, src/lib/components/forms/suggestion-box/terra-suggestion-box.component.spec.ts, src/lib/components/stopwatch/terra-stopwatch.component.spec.ts, src/lib/components/tables/data-table/terra-data-table.component.spec.ts, src/lib/components/tables/group-function/terra-group-function.component.spec.ts
=> feature(testing): remove unused import of HttpClientModule from some TestingModules

CHANGELOG.md, src/lib/styles/material/_form-field.scss
Testing
Responsiveness
Responsiveness
Documentation
=> fix(form-field-styles): add ng-touched to ng-invalid

src/app/app.component.scss, src/app/app.component.ts, src/app/app.module.ts, src/app/showcase/showcase.component.html, src/app/showcase/showcase.component.scss, src/app/showcase/showcase.component.ts, src/app/translation/l10n.config.ts
=> feature(prettier): apply prettier to src/app

src/assets/lang/locale-de.json, src/assets/lang/locale-en.json
=> feature(prettier): apply prettier to src/assets

CHANGELOG.md, src/app/app.component.html, src/app/app.module.ts, src/lib/styles/material/_checkbox.scss, src/lib/styles/material/_table.scss, src/lib/styles/styles.scss
Testing
Responsiveness
Responsiveness
----
Documentation
Testing
=> feature (mat-checkbox): add new styles 

src/lib/environments/environment.test.ts, src/lib/environments/environment.ts
=> feature(prettier) apply prettier to src/lib/environment

src/lib/components/layouts/portlet/terra-portlet.component.scss, src/lib/styles/material/_table.scss
Testing
Responsiveness
Responsiveness
----
Documentation
Testing
=> feature (mat-table): increased header, footer and paginator contrast

src/lib/styles/material/_table.scss
Testing
Responsiveness
Responsiveness
----
Documentation
Testing
=> fix (table): remove overflow for sticky header/footer

src/lib/styles/material/_table.scss
Testing
Responsiveness
Responsiveness
----
Documentation
Testing
=> fix (checkbox): adjust margin-bottom in table

src/lib/styles/material/_table.scss
Testing
Responsiveness
Responsiveness
----
Documentation
Testing
=> fix (table): adjust border-top and min-height for footer 

src/lib/helpers/activated-route.helper.ts, src/lib/helpers/clipboard.helper.ts, src/lib/helpers/dispatch.helper.ts, src/lib/helpers/download.helper.ts, src/lib/helpers/enums/button-color.enum.ts, src/lib/helpers/enums/indicator-label-type.enum.ts, src/lib/helpers/enums/terra-placement.enum.ts, src/lib/helpers/fileType.helper.ts, src/lib/helpers/number.helper.ts, src/lib/helpers/object.helper.ts, src/lib/helpers/path.helper.ts, src/lib/helpers/query-param.helper.ts, src/lib/helpers/regex/terra-regex.ts, src/lib/helpers/string.helper.ts, src/lib/helpers/terra-converter.helper.ts, src/lib/helpers/terra-label-tooltip.directive.ts, src/lib/helpers/terra-pdf.helper.ts, src/lib/helpers/tests/number.helper.spec.ts, src/lib/helpers/tests/path.helper.spec.ts, src/lib/helpers/tests/string.helper.spec.ts, src/lib/helpers/two-column.helper.ts, src/lib/helpers/url.helper.ts
=> feature(prettier): apply prettier to src/lib/helpers

CHANGELOG.md, src/lib/components/buttons/button/data/terra-button.interface.ts, src/lib/components/buttons/button/terra-button.component.ts, src/lib/components/buttons/toggle/terra-toggle.component.ts, src/lib/components/editors/base-editor/terra-base-editor.component.ts, src/lib/components/forms/checkbox/terra-checkbox.component.ts, src/lib/components/forms/input/terra-input.component.ts, src/lib/components/info/terra-info.component.ts, src/lib/components/tables/data-table/interfaces/terra-data-table-cell.interface.ts, src/lib/components/tables/data-table/interfaces/terra-data-table-header-cell.interface.ts, src/lib/components/tables/simple/cell/terra-simple-table-cell.interface.ts, src/lib/components/tooltip/tooltip.directive.ts, src/lib/components/tree/node-tree/data/terra-node.interface.ts
Testing
Responsiveness
Responsiveness
----
Documentation
=> feature (tooltip): removed warning and all deprecations

src/lib/utils/http-param-encoder.ts, src/lib/utils/http-params.spec.ts, src/lib/utils/http-params.ts, src/lib/utils/window.ts
=> feature(prettier): apply prettier to src/lib/utils

src/lib/validators/iban-validator.spec.ts, src/lib/validators/iban-validator.ts, src/lib/validators/terra-decimal-validator.ts, src/lib/validators/unique-values-validator.spec.ts, src/lib/validators/unique-values-validator.ts, src/lib/validators/validators.spec.ts, src/lib/validators/validators.ts
=> feature(prettier): apply prettier to src/lib/validators

src/lib/service/data/exception.interface.ts, src/lib/service/index.ts, src/lib/service/model-cache.ts
=> feature(prettier): apply prettier to src/lib/service

src/lib/models/terra-key-value-pair.interface.ts, src/lib/models/terra-key-value.interface.ts
=> feature(prettier): apply prettier to src/lib/models

src/lib/http-interceptors/auth.interceptor.spec.ts, src/lib/http-interceptors/auth.interceptor.ts, src/lib/http-interceptors/error.interceptor.spec.ts, src/lib/http-interceptors/error.interceptor.ts, src/lib/http-interceptors/interceptor-providers.ts, src/lib/http-interceptors/loading.interceptor.spec.ts, src/lib/http-interceptors/loading.interceptor.ts
=> feature(prettier) apply prettier to src/lib/http-interceptors

src/lib/testing/file-input/file-data.ts, src/lib/testing/file-input/terra-frontend-storage-service-stub.ts, src/lib/testing/mock-activated-route.ts, src/lib/testing/mock-buttons.ts, src/lib/testing/mock-change-detector-ref.ts, src/lib/testing/mock-element-ref.ts, src/lib/testing/mock-router.ts, src/lib/testing/mock-tags.ts, src/lib/testing/mock-translation-module.ts, src/lib/testing/mock-translation-service.ts
=> feature(prettier): apply prettier to src/lib/testing

CHANGELOG.md, src/assets/lang/locale-de.json, src/assets/lang/locale-en.json, src/lib/components/table/index.ts, src/lib/components/table/terra-mat-paginator-intl.ts
Testing
Responsiveness
Responsiveness
----
Documentation
Testing
=> add terra mat paginator intl

CHANGELOG.md, src/lib/components/tooltip/tooltip.directive.spec.ts, src/lib/components/tooltip/tooltip.directive.ts
Testing
----
Documentation
Testing
=> fix(tooltip): subscribe to router events in ngOnInit, not ngOnChanges

CHANGELOG.md, src/lib/components/layouts/taglist/terra-taglist.component.scss
related to: https://forum.plentymarkets.com/t/terratagselect-wrap-text/597212/
Testing
Responsiveness
Responsiveness
----
Documentation
=> fix(terra-taglist): add flex-wrap

src/lib/components/tooltip/tooltip.directive.spec.ts, src/lib/helpers/tests/sort.helper.spec.ts
=> feature(tooltip): add test for tooltips provided by TemplateRef

src/lib/helpers/query-param.helper.ts, src/lib/helpers/tests/query-param.helper.spec.ts
=> testing: query param helper

CHANGELOG.md, src/lib/styles/material/_table.scss
=> fix (mat-table): remove cursor:pointer from table row

src/lib/components/forms/input/time-picker/terra-time-picker.component.spec.ts, src/lib/components/forms/input/time-picker/terra-time-picker.component.ts
=> feature(time-picker): unit tests

src/lib/helpers/tests/url.helper.spec.ts
=> feature(UrlHelper): add unit test specs for all methods

CHANGELOG.md, src/lib/components/forms/checkbox-group/checkbox-group.component.ts, src/lib/components/forms/multi-check-box/data/terra-multi-check-box-value.interface.ts, src/lib/components/forms/multi-check-box/terra-multi-check-box.component.ts
=> feature(multi-select): deprecate CheckboxGroup- and MultiCheckboxComponent

package-lock.json, src/lib/components/data/terra-base-parameter.interface.ts, src/lib/components/data/terra-base.data.ts
=> feature(prettier): apply prettier to src/lib/components/data

src/lib/components/layouts/info-box/example/terra-info-box.component.example.html, src/lib/components/layouts/info-box/example/terra-info-box.component.example.md, src/lib/components/layouts/info-box/example/terra-info-box.component.example.ts, src/lib/components/layouts/info-box/terra-info-box.component.html, src/lib/components/layouts/info-box/terra-info-box.component.scss, src/lib/components/layouts/info-box/terra-info-box.component.spec.ts, src/lib/components/layouts/info-box/terra-info-box.component.ts
=> feature(prettier): apply prettier to src/lib/component/layouts/info-box

src/lib/components/layouts/column-container/column-container.config.ts, src/lib/components/layouts/column-container/three-columns/example/terra-three-column-container.component.example.html, src/lib/components/layouts/column-container/three-columns/example/terra-three-column-container.component.example.ts, src/lib/components/layouts/column-container/three-columns/terra-three-columns-container.component.scss, src/lib/components/layouts/column-container/three-columns/terra-three-columns-container.component.spec.ts, src/lib/components/layouts/column-container/three-columns/terra-three-columns-container.component.ts, src/lib/components/layouts/column-container/two-columns/example/terra-two-column-container.component.example.ts, src/lib/components/layouts/column-container/two-columns/terra-two-columns-container.component.scss, src/lib/components/layouts/column-container/two-columns/terra-two-columns-container.component.spec.ts, src/lib/components/layouts/column-container/two-columns/terra-two-columns-container.component.ts, src/lib/components/layouts/column-container/two-columns/terra-two-columns-container.directive.spec.ts, src/lib/components/layouts/column-container/two-columns/terra-two-columns-container.directive.ts
=> feature(prettier): apply prettier to src/lib/component/layouts/column-container

src/lib/components/info/example/terra-info.component.example.html, src/lib/components/info/example/terra-info.component.example.scss, src/lib/components/info/example/terra-info.component.example.ts, src/lib/components/info/terra-info.component.html, src/lib/components/info/terra-info.component.scss, src/lib/components/info/terra-info.component.spec.ts, src/lib/components/info/terra-info.component.ts
=> feature(prettier): apply prettier to src/lib/component/info

src/lib/components/indicator/terra-indicator.component.html, src/lib/components/indicator/terra-indicator.component.scss, src/lib/components/indicator/terra-indicator.component.spec.ts, src/lib/components/indicator/terra-indicator.component.ts
=> feature(prettier): apply prettier to src/lib/component/indicator

src/lib/components/forms/terra-forms.example.html, src/lib/components/forms/terra-forms.example.ts
=> feature(prettier): apply prettier to src/lib/components/forms

src/lib/components/forms/tag-select/example/terra-tag-select.component.example.ts, src/lib/components/forms/tag-select/terra-tag-select.component.html, src/lib/components/forms/tag-select/terra-tag-select.component.scss, src/lib/components/forms/tag-select/terra-tag-select.component.ts
=> feature(prettier): apply prettier to src/lib/components/forms/tag-select

src/lib/components/forms/suggestion-box/data/terra-suggestion-box.interface.ts, src/lib/components/forms/suggestion-box/example/terra-suggestion-box.component.example.html, src/lib/components/forms/suggestion-box/example/terra-suggestion-box.component.example.ts, src/lib/components/forms/suggestion-box/terra-suggestion-box.component.html, src/lib/components/forms/suggestion-box/terra-suggestion-box.component.scss, src/lib/components/forms/suggestion-box/terra-suggestion-box.component.spec.ts, src/lib/components/forms/suggestion-box/terra-suggestion-box.component.ts
=> feature(prettier): apply prettier to src/lib/components/forms/suggestion-box

src/lib/components/forms/select-box/data/allowed.colors.enum.ts, src/lib/components/forms/select-box/data/terra-select-box.interface.ts, src/lib/components/forms/select-box/directive/select-sort.directive.spec.ts, src/lib/components/forms/select-box/directive/select-sort.directive.ts, src/lib/components/forms/select-box/example/terra-select-box.component.example.html, src/lib/components/forms/select-box/example/terra-select-box.component.example.ts, src/lib/components/forms/select-box/terra-select-box.component.html, src/lib/components/forms/select-box/terra-select-box.component.scss, src/lib/components/forms/select-box/terra-select-box.component.spec.ts, src/lib/components/forms/select-box/terra-select-box.component.ts
=> feature(prettier): apply prettier to src/lib/components/forms/select-box

src/lib/components/forms/radio-button/example/terra-radio-button.component.example.html, src/lib/components/forms/radio-button/example/terra-radio-button.component.example.ts, src/lib/components/forms/radio-button/terra-radio-button.component.html, src/lib/components/forms/radio-button/terra-radio-button.component.scss, src/lib/components/forms/radio-button/terra-radio-button.component.ts
=> feature(prettier): apply prettier to src/lib/components/forms/radio-button

src/lib/components/forms/dynamic-form/data/terra-form-field-base-container.ts, src/lib/components/forms/dynamic-form/data/terra-form-field-base.ts, src/lib/components/forms/dynamic-form/data/terra-form-field-category-picker.ts, src/lib/components/forms/dynamic-form/data/terra-form-field-check-box.ts, src/lib/components/forms/dynamic-form/data/terra-form-field-code-editor.ts, src/lib/components/forms/dynamic-form/data/terra-form-field-color-picker.ts, src/lib/components/forms/dynamic-form/data/terra-form-field-date-picker.ts, src/lib/components/forms/dynamic-form/data/terra-form-field-horizontal-container.ts, src/lib/components/forms/dynamic-form/data/terra-form-field-input-double.ts, src/lib/components/forms/dynamic-form/data/terra-form-field-input-file.ts, src/lib/components/forms/dynamic-form/data/terra-form-field-input-number.ts, src/lib/components/forms/dynamic-form/data/terra-form-field-input-text.ts, src/lib/components/forms/dynamic-form/data/terra-form-field-multi-check-box.ts, src/lib/components/forms/dynamic-form/data/terra-form-field-note-editor.ts, src/lib/components/forms/dynamic-form/data/terra-form-field-select-box.ts, src/lib/components/forms/dynamic-form/data/terra-form-field-text-area.ts, src/lib/components/forms/dynamic-form/data/terra-form-field-vertical-container.ts, src/lib/components/forms/dynamic-form/dynamic-switch/terra-dynamic-switch.component.html, src/lib/components/forms/dynamic-form/dynamic-switch/terra-dynamic-switch.component.scss, src/lib/components/forms/dynamic-form/dynamic-switch/terra-dynamic-switch.component.ts, src/lib/components/forms/dynamic-form/enum/terra-control-type.enum.ts, src/lib/components/forms/dynamic-form/handler/terra-dynamic-form-functions.handler.ts, src/lib/components/forms/dynamic-form/service/terra-dynamic-form.service.ts, src/lib/components/forms/dynamic-form/service/terra-form-field-control.service.ts, src/lib/components/forms/dynamic-form/service/terra-json-to-form-field.service.ts, src/lib/components/forms/dynamic-form/terra-dynamic-form.component.html, src/lib/components/forms/dynamic-form/terra-dynamic-form.component.scss, src/lib/components/forms/dynamic-form/terra-dynamic-form.component.ts
=> feature(prettier): apply prettier to src/lib/components/forms/dynamic-form

src/lib/components/forms/checkbox-group/checkbox-group.component.html, src/lib/components/forms/checkbox-group/checkbox-group.component.spec.ts, src/lib/components/forms/checkbox-group/checkbox-group.component.ts, src/lib/components/forms/checkbox-group/example/checkbox-group.component.example.html, src/lib/components/forms/checkbox-group/example/checkbox-group.component.example.ts
=> feature(prettier): apply prettier to src/lib/components/forms/checkbox-group

src/lib/components/interactables/draggable.directive.ts, src/lib/components/interactables/draggableOptions.interface.ts, src/lib/components/interactables/dropEvent.interface.ts, src/lib/components/interactables/dropzone.directive.ts, src/lib/components/interactables/gridOptions.interface.ts, src/lib/components/interactables/inertiaOptions.interface.ts, src/lib/components/interactables/interact.module.ts, src/lib/components/interactables/interactableOptions.interface.ts, src/lib/components/interactables/resizable.directive.ts, src/lib/components/interactables/resizeOptions.interface.ts, src/lib/components/interactables/restrictOptions.interface.ts
=> feature(prettier): apply prettier to src/lib/component/interactables

src/lib/components/forms/checkbox/example/terra-checkbox.component.example.html, src/lib/components/forms/checkbox/example/terra-checkbox.component.example.ts, src/lib/components/forms/checkbox/terra-checkbox.component.html, src/lib/components/forms/checkbox/terra-checkbox.component.scss, src/lib/components/forms/checkbox/terra-checkbox.component.spec.ts, src/lib/components/forms/checkbox/terra-checkbox.component.ts
=> feature(prettier): apply prettier to src/lib/components/forms/checkbox

src/lib/components/filter/example/filter.component.example.html, src/lib/components/filter/example/filter.component.example.ts, src/lib/components/filter/example/terra-filter.component.example.html, src/lib/components/filter/example/terra-filter.component.example.ts, src/lib/components/filter/filter.component.html, src/lib/components/filter/filter.component.spec.ts, src/lib/components/filter/filter.component.ts, src/lib/components/filter/terra-filter.component.html, src/lib/components/filter/terra-filter.component.ts
=> feature(prettier): apply prettier to src/lib/components/filter

src/lib/components/file-browser/example/terra-file-browser.component.example.ts, src/lib/components/file-browser/file-list/file-list.component.html, src/lib/components/file-browser/file-list/file-list.component.scss, src/lib/components/file-browser/file-list/file-list.component.ts, src/lib/components/file-browser/image-preview/image-preview.component.html, src/lib/components/file-browser/image-preview/image-preview.component.scss, src/lib/components/file-browser/image-preview/image-preview.component.ts, src/lib/components/file-browser/model/s3-storage-object.interface.ts, src/lib/components/file-browser/model/terra-image-metadata.interface.ts, src/lib/components/file-browser/model/terra-storage-object-list.ts, src/lib/components/file-browser/model/terra-storage-object.ts, src/lib/components/file-browser/model/terra-upload-item.ts, src/lib/components/file-browser/model/terra-upload-progress.ts, src/lib/components/file-browser/model/terra-upload-queue.ts, src/lib/components/file-browser/terra-base-metadata-storage.interface.ts, src/lib/components/file-browser/terra-base-private-storage.interface.ts, src/lib/components/file-browser/terra-base-storage.interface.ts, src/lib/components/file-browser/terra-file-browser.component.glob.scss, src/lib/components/file-browser/terra-file-browser.component.html, src/lib/components/file-browser/terra-file-browser.component.ts, src/lib/components/file-browser/terra-file-browser.service.ts, src/lib/components/file-browser/terra-frontend-storage.service.ts
=> feature(prettier): apply prettier to src/lib/components/file-browser

src/lib/components/editors/base-editor/terra-base-editor.component.glob.scss, src/lib/components/editors/base-editor/terra-base-editor.component.html, src/lib/components/editors/base-editor/terra-base-editor.component.ts, src/lib/components/editors/ck-editor/ck-editor-full.directive.spec.ts, src/lib/components/editors/ck-editor/ck-editor.directive.ts, src/lib/components/editors/ck-editor/example/ck-editor-directive-example.component.html, src/lib/components/editors/ck-editor/example/ck-editor-directive-example.component.ts, src/lib/components/editors/ck-editor/presets/ck-editor-full-preset.ts, src/lib/components/editors/ck-editor/presets/ck-editor-minimum-preset.ts, src/lib/components/editors/code-editor/example/terra-code-editor.component.example.html, src/lib/components/editors/code-editor/example/terra-code-editor.component.example.scss, src/lib/components/editors/code-editor/example/terra-code-editor.component.example.ts, src/lib/components/editors/code-editor/helper/html-linter-message.interface.ts, src/lib/components/editors/code-editor/helper/html-linter-rule.enum.ts, src/lib/components/editors/code-editor/helper/html-linter.helper.ts, src/lib/components/editors/code-editor/terra-code-editor.component.html, src/lib/components/editors/code-editor/terra-code-editor.component.scss, src/lib/components/editors/code-editor/terra-code-editor.component.spec.ts, src/lib/components/editors/code-editor/terra-code-editor.component.ts, src/lib/components/editors/note-editor/example/terra-note-editor.component.example.html, src/lib/components/editors/note-editor/example/terra-note-editor.component.example.ts, src/lib/components/editors/note-editor/terra-note-editor.component.html, src/lib/components/editors/note-editor/terra-note-editor.component.ts, src/lib/components/editors/syntax-editor/data/terra-syntax-editor.data.ts, src/lib/components/editors/syntax-editor/example/terra-syntax-editor.component.example.html, src/lib/components/editors/syntax-editor/example/terra-syntax-editor.component.example.ts, src/lib/components/editors/syntax-editor/terra-syntax-editor.component.html, src/lib/components/editors/syntax-editor/terra-syntax-editor.component.ts
=> feature(prettier): apply prettier to src/lib/components/editors

package-lock.json, src/lib/components/data-picker/category-picker/config/category-tree.config.ts, src/lib/components/data-picker/category-picker/data/category-client.interface.ts, src/lib/components/data-picker/category-picker/data/category-data.interface.ts, src/lib/components/data-picker/category-picker/data/category-detail-data.interface.ts, src/lib/components/data-picker/category-picker/data/category-value.interface.ts, src/lib/components/data-picker/category-picker/service/terra-category-picker-base.service.ts, src/lib/components/data-picker/category-picker/terra-category-picker.component.html, src/lib/components/data-picker/category-picker/terra-category-picker.component.ts, src/lib/components/data-picker/nested-data-picker/config/nested-data-tree.config.ts, src/lib/components/data-picker/nested-data-picker/data/nested-data.interface.ts, src/lib/components/data-picker/nested-data-picker/data/nested-detail-data.interface.ts, src/lib/components/data-picker/nested-data-picker/data/nested-value.interface.ts, src/lib/components/data-picker/nested-data-picker/example/service/terra-nested-data-picker.service.example.ts, src/lib/components/data-picker/nested-data-picker/example/terra-nested-data-picker.component.example.html, src/lib/components/data-picker/nested-data-picker/example/terra-nested-data-picker.component.example.ts, src/lib/components/data-picker/nested-data-picker/service/terra-nested-data-picker-base.service.ts, src/lib/components/data-picker/nested-data-picker/terra-nested-data-picker.component.html, src/lib/components/data-picker/nested-data-picker/terra-nested-data-picker.component.scss, src/lib/components/data-picker/nested-data-picker/terra-nested-data-picker.component.ts
=> feature(prettier): apply prettier to src/lib/components/data-picker

src/lib/components/buttons/button-with-options/example/terra-button-with-options.component.example.html, src/lib/components/buttons/button-with-options/example/terra-button-with-options.component.example.ts, src/lib/components/buttons/button-with-options/terra-button-with-options.component.html, src/lib/components/buttons/button-with-options/terra-button-with-options.component.scss, src/lib/components/buttons/button-with-options/terra-button-with-options.component.ts, src/lib/components/buttons/button/data/terra-button.interface.ts, src/lib/components/buttons/button/example/terra-button.component.example.html, src/lib/components/buttons/button/example/terra-button.component.example.ts, src/lib/components/buttons/button/terra-button.component.html, src/lib/components/buttons/button/terra-button.component.scss, src/lib/components/buttons/button/terra-button.component.ts, src/lib/components/buttons/file-chooser/terra-file-chooser.component.html, src/lib/components/buttons/file-chooser/terra-file-chooser.component.scss, src/lib/components/buttons/file-chooser/terra-file-chooser.component.ts, src/lib/components/buttons/toggle/example/terra-toggle.component.example.html, src/lib/components/buttons/toggle/example/terra-toggle.component.example.ts, src/lib/components/buttons/toggle/terra-toggle.component.html, src/lib/components/buttons/toggle/terra-toggle.component.scss, src/lib/components/buttons/toggle/terra-toggle.component.ts
=> feature(prettier): apply prettier to src/lib/components/buttons

src/lib/components/breadcrumbs/service/terra-breadcrumbs.service.ts, src/lib/components/breadcrumbs/terra-breadcrumb-container.ts, src/lib/components/breadcrumbs/terra-breadcrumb.ts, src/lib/components/breadcrumbs/terra-breadcrumbs.component.html, src/lib/components/breadcrumbs/terra-breadcrumbs.component.scss, src/lib/components/breadcrumbs/terra-breadcrumbs.component.ts
=> feature(prettier): apply prettier to src/lib/components/breadcrumbs

src/lib/components/alert/alert-type.enum.ts, src/lib/components/alert/alert.service.spec.ts, src/lib/components/alert/alert.service.ts, src/lib/components/alert/data/terra-alert.interface.ts, src/lib/components/alert/example/terra-alert.component.example.html, src/lib/components/alert/example/terra-alert.component.example.ts, src/lib/components/alert/terra-alert-panel.component.glob.scss, src/lib/components/alert/terra-alert-panel.component.html, src/lib/components/alert/terra-alert-panel.component.ts, src/lib/components/alert/terra-alert.component.ts
=> feature(prettier): apply prettier to src/lib/components/alert

src/lib/components/layouts/overlay/data/terra-overlay-button.interface.ts, src/lib/components/layouts/overlay/example/terra-overlay.component.example.html, src/lib/components/layouts/overlay/example/terra-overlay.component.example.ts, src/lib/components/layouts/overlay/terra-overlay.component.html, src/lib/components/layouts/overlay/terra-overlay.component.scss, src/lib/components/layouts/overlay/terra-overlay.component.spec.ts, src/lib/components/layouts/overlay/terra-overlay.component.ts
=> feature(prettier): apply prettier to src/lib/component/layouts/overlay

src/lib/components/layouts/portlet/example/terra-portlet.component.example.html, src/lib/components/layouts/portlet/example/terra-portlet.component.example.ts, src/lib/components/layouts/portlet/terra-portlet.component.html, src/lib/components/layouts/portlet/terra-portlet.component.scss, src/lib/components/layouts/portlet/terra-portlet.component.spec.ts, src/lib/components/layouts/portlet/terra-portlet.component.ts
=> feature(prettier): apply prettier to src/lib/component/layouts/portlet

src/lib/components/layouts/tag/data/terra-tag-name.interface.ts, src/lib/components/layouts/tag/data/terra-tag.interface.ts, src/lib/components/layouts/tag/example/terra-tag.component.example.html, src/lib/components/layouts/tag/example/terra-tag.component.example.md, src/lib/components/layouts/tag/example/terra-tag.component.example.scss, src/lib/components/layouts/tag/example/terra-tag.component.example.ts, src/lib/components/layouts/tag/terra-tag.component.html, src/lib/components/layouts/tag/terra-tag.component.scss, src/lib/components/layouts/tag/terra-tag.component.spec.ts, src/lib/components/layouts/tag/terra-tag.component.ts
=> feature(prettier): apply prettier to src/lib/component/layouts/tag

src/lib/components/layouts/taglist/example/terra-taglist.component.example.ts, src/lib/components/layouts/taglist/terra-taglist.component.html, src/lib/components/layouts/taglist/terra-taglist.component.spec.ts, src/lib/components/layouts/taglist/terra-taglist.component.ts
=> feature(prettier): apply prettier to src/lib/component/layouts/taglist

src/lib/components/loading-spinner/example/terra-loading-spinner.component.example.ts, src/lib/components/loading-spinner/service/terra-loading-spinner.service.spec.ts, src/lib/components/loading-spinner/service/terra-loading-spinner.service.ts, src/lib/components/loading-spinner/terra-loading-spinner.component.scss, src/lib/components/loading-spinner/terra-loading-spinner.component.ts
=> feature(prettier): apply prettier to src/lib/component/loading-spinner

src/lib/components/note/example/terra-note.component.example.html, src/lib/components/note/example/terra-note.component.example.ts, src/lib/components/note/terra-note.component.html, src/lib/components/note/terra-note.component.scss, src/lib/components/note/terra-note.component.ts
=> feature(prettier): apply prettier to src/lib/component/note

CHANGELOG.md, src/lib/components/data-picker/category-picker/terra-category-picker.component.html, src/lib/components/data-picker/category-picker/terra-category-picker.component.spec.ts, src/lib/components/data-picker/category-picker/terra-category-picker.component.ts, src/lib/components/tree/node-tree/data/terra-node.interface.ts, src/lib/components/tree/node-tree/node/terra-node.component.html, src/lib/components/tree/node-tree/node/terra-node.component.spec.ts, src/lib/components/tree/node-tree/node/terra-node.component.ts
@plentymarkets/cms lentymarkets/team-terra
@plentymarkets/ceres-io 
Testing
Responsiveness
Responsiveness
----
Documentation
Testing
=> enabled tooltips for nodes in category-picker

src/lib/components/pager/data/terra-pager-default-paging-sizes.ts, src/lib/components/pager/data/terra-pager.interface.ts, src/lib/components/pager/data/terra-pager.parameter.interface.ts, src/lib/components/pager/example/terra-pager.component.example.ts, src/lib/components/pager/terra-pager.component.html, src/lib/components/pager/terra-pager.component.scss, src/lib/components/pager/terra-pager.component.ts
=> feature(prettier): apply prettier to src/lib/component/pager

src/lib/components/table/filter.spec.ts, src/lib/components/table/filter.ts, src/lib/components/table/has-paginator.interface.ts, src/lib/components/table/has-sorting.interface.ts, src/lib/components/table/request-parameter.interface.ts, src/lib/components/table/table-data-source.spec.ts, src/lib/components/table/table-data-source.ts, src/lib/components/table/table-paging-data-source.spec.ts, src/lib/components/table/table-paging-data-source.ts, src/lib/components/table/table-paging-sorting-data-source.spec.ts, src/lib/components/table/table-paging-sorting-data-source.ts, src/lib/components/table/table-settings/dialog/table-settings-dialog.component.html, src/lib/components/table/table-settings/dialog/table-settings-dialog.component.spec.ts, src/lib/components/table/table-settings/dialog/table-settings-dialog.component.ts, src/lib/components/table/table-settings/dialog/table-settings-dialog.glob.scss, src/lib/components/table/table-settings/interface/column.interface.ts, src/lib/components/table/table-settings/interface/table-settings-dialog-data.interface.ts, src/lib/components/table/table-settings/table-settings.component.html, src/lib/components/table/table-settings/table-settings.component.spec.ts, src/lib/components/table/table-settings/table-settings.component.ts, src/lib/components/table/table-sorting-data-source.spec.ts, src/lib/components/table/table-sorting-data-source.ts, src/lib/components/table/terra-mat-paginator-intl.spec.ts, src/lib/components/table/terra-mat-paginator-intl.ts
=> feature(prettier): apply prettier to src/lib/components/table

src/lib/components/tooltip/example/tooltip-directive.example.html, src/lib/components/tooltip/example/tooltip-directive.example.ts, src/lib/components/tooltip/tooltip.directive.spec.ts, src/lib/components/tooltip/tooltip.directive.ts
=> feature(prettier): apply prettier to src/lib/components/tooltip

src/lib/components/tree/base/terra-base-tree.component.ts, src/lib/components/tree/checkbox-tree/data/terra-checkbox-tree-leaf-state.ts, src/lib/components/tree/checkbox-tree/example/terra-checkbox-tree.component.example.html, src/lib/components/tree/checkbox-tree/example/terra-checkbox-tree.component.example.scss, src/lib/components/tree/checkbox-tree/example/terra-checkbox-tree.component.example.ts, src/lib/components/tree/checkbox-tree/terra-checkbox-tree.component.html, src/lib/components/tree/checkbox-tree/terra-checkbox-tree.component.scss, src/lib/components/tree/checkbox-tree/terra-checkbox-tree.component.ts, src/lib/components/tree/leaf/terra-checkbox-leaf.interface.ts, src/lib/components/tree/leaf/terra-leaf.interface.ts, src/lib/components/tree/node-tree/data/terra-node-tree.config.ts, src/lib/components/tree/node-tree/data/terra-node.interface.ts, src/lib/components/tree/node-tree/example/terra-node-tree.component.example.html, src/lib/components/tree/node-tree/example/terra-node-tree.component.example.ts, src/lib/components/tree/node-tree/helper/terra-node-tree.helper.ts, src/lib/components/tree/node-tree/node/terra-node.component.html, src/lib/components/tree/node-tree/node/terra-node.component.scss, src/lib/components/tree/node-tree/node/terra-node.component.spec.ts, src/lib/components/tree/node-tree/node/terra-node.component.ts, src/lib/components/tree/node-tree/terra-node-tree.component.html, src/lib/components/tree/node-tree/terra-node-tree.component.scss, src/lib/components/tree/node-tree/terra-node-tree.component.ts
=> feature(prettier): apply prettier to src/lib/components/tree

src/lib/components/component-collection.ts, src/lib/components/directive-collection.ts, src/lib/components/example-collection.ts
=> feature(prettier): apply prettier to src/lib/components

src/lib/components/stopwatch/example/terra-stopwatch.component.example.html, src/lib/components/stopwatch/example/terra-stopwatch.component.example.ts, src/lib/components/stopwatch/terra-stopwatch.component.html, src/lib/components/stopwatch/terra-stopwatch.component.spec.ts, src/lib/components/stopwatch/terra-stopwatch.component.ts
=> feature(prettier): apply prettier to src/lib/components/stopwatch

CHANGELOG.md, package.json, src/lib/components/forms/dynamic-form/service/terra-json-to-form-field.service.ts, tslint.json
=> feature(prettier): finalizing work

package-lock.json
=> fix(deps / security vulnerability): terser-webpack-plugin

package-lock.json
=> fix(deps): npm update dot-prop --depth 4

package-lock.json, package.json, tslint.json
=> feature(deps): install new version of the lint rules that comply to prettier's styles

CHANGELOG.md, src/lib/styles/material/_tree.scss, src/lib/styles/styles.scss
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature (mat-tree): added styles

CHANGELOG.md, src/assets/lang/locale-de.json, src/assets/lang/locale-en.json, src/lib/components/table/table-settings/dialog/table-settings-dialog.component.html, src/lib/components/table/table-settings/table-settings.component.html
Testing
-   [ ] Chrome
-   [ ] Safari
-   [ ] Chrome
-   [ ] Safari
---
Documentation
=> change l10n

CHANGELOG.md, src/lib/components/forms/input/color-picker/terra-color-picker.component.ts, src/lib/components/layouts/tag/terra-tag.component.ts, src/lib/helpers/color.helper.spec.ts, src/lib/helpers/color.helper.ts, src/lib/helpers/index.ts
Testing
---
Documentation
-   [x] JSDoc (optional: relevant for every change which influences the API)
Testing
=> feature(helpers): export color helper

CHANGELOG.md, src/lib/styles/material/_checkbox.scss
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> fix (mat-checkbox): styles for disabled when checked or indetermiante

CHANGELOG.md, src/lib/components/forms/checkbox/terra-checkbox.component.ts
Documentation
-   [x] JSDoc (optional: relevant for every change which influences the API)
-   [ ] [Google spreadsheet](https://docs.google.com/spreadsheets/d/1OINnux8TEoitV-qdAxqUQaf9oGI_fqFVwfRWenRFfhI/edit#gid=0) (relevant when deprecating public APIs or features)
=> feature(checkbox): deprecate terra-checkbox

CHANGELOG.md, src/lib/styles/styles.scss
=> fix(styles): no outline on focused elements

CHANGELOG.md, src/lib/components/forms/form/form-entry-list/terra-form-entry-list.component.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> add manual mark as dirty

CHANGELOG.md, src/lib/components/layouts/info-box/terra-info-box.component.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature (info-box): set terra-info-box to deprecated

CHANGELOG.md, src/lib/components/data/terra-base-parameter.interface.ts, src/lib/components/data/terra-base.data.ts, src/lib/components/editors/base-editor/terra-base-editor.component.ts, src/lib/components/editors/code-editor/terra-code-editor.component.ts, src/lib/components/editors/note-editor/terra-note-editor.component.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature (editors): deprecate note-, code- and base-editor

CHANGELOG.md, src/lib/components/tree/base/terra-base-tree.component.ts, src/lib/components/tree/checkbox-tree/data/terra-checkbox-tree-leaf-state.ts, src/lib/components/tree/checkbox-tree/terra-checkbox-tree.component.ts, src/lib/components/tree/leaf/terra-checkbox-leaf.interface.ts, src/lib/components/tree/leaf/terra-leaf.interface.ts, src/lib/components/tree/node-tree/data/terra-node-tree.config.ts, src/lib/components/tree/node-tree/data/terra-node.interface.ts, src/lib/components/tree/node-tree/helper/terra-node-tree.helper.ts, src/lib/components/tree/node-tree/node/terra-node.component.ts, src/lib/components/tree/node-tree/terra-node-tree.component.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> mark trees and all related stuff as deprecated

CHANGELOG.md, src/lib/components/toolbar/base-toolbar/terra-base-toolbar.component.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature (base-toolbar): set base toolbar to deprecated

CHANGELOG.md, src/lib/components/indicator/terra-indicator.component.ts, src/lib/helpers/enums/indicator-label-type.enum.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature (terra-indicator): set terra-indicator to deprecated

CHANGELOG.md, src/lib/components/tables/simple/cell/terra-simple-table-cell.interface.ts, src/lib/components/tables/simple/cell/terra-simple-table-header-cell.interface.ts, src/lib/components/tables/simple/row/terra-simple-table-row.interface.ts, src/lib/components/tables/simple/terra-simple-table.component.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature (simple-table): set simple table to deprecated

CHANGELOG.md, src/lib/components/info/terra-info.component.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature (terra-info-component): terra info component deprecated

CHANGELOG.md, src/lib/components/tables/terra-base-table.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature (base-table): set base table to deprecated

CHANGELOG.md, src/lib/components/note/terra-note.component.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature (terra-note): set terra-note to deprecated

CHANGELOG.md, src/lib/components/layouts/card/terra-card.component.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> fetaure(terra-card): terra-card is set to deprecated

CHANGELOG.md, src/lib/components/forms/tag-select/terra-tag-select.component.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature (tag-select): deprecate tag select

src/lib/components/pager/data/terra-pager-default-paging-sizes.ts, src/lib/components/pager/data/terra-pager.interface.ts, src/lib/components/pager/data/terra-pager.parameter.interface.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature (pager): added deprecation to pager interfaces

src/lib/components/pager/data/terra-pager.interface.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> fix (pager-interface): removed deprecation from pager interface

CHANGELOG.md, src/lib/components/layouts/tag/data/terra-tag-name.interface.ts, src/lib/components/layouts/tag/data/terra-tag.interface.ts, src/lib/components/layouts/tag/terra-tag.component.ts, src/lib/components/layouts/taglist/terra-taglist.component.ts
Documentation
-   [x] JSDoc (optional: relevant for every change which influences the API)
-   [x] [Google spreadsheet](https://docs.google.com/spreadsheets/d/1OINnux8TEoitV-qdAxqUQaf9oGI_fqFVwfRWenRFfhI/edit#gid=0) (relevant when deprecating public APIs or features)
=> feature(tags): deprecate tag and tag-list

CHANGELOG.md, src/lib/components/toolbar/base-toolbar/terra-base-toolbar.component.ts
Documentation
-   [ ] [Google spreadsheet](https://docs.google.com/spreadsheets/d/1OINnux8TEoitV-qdAxqUQaf9oGI_fqFVwfRWenRFfhI/edit#gid=0) (relevant when deprecating public APIs or features)
=> feature(toolbar): removed input deprecated `inputIsBreadcrumbs`

CHANGELOG.md, src/lib/public-api.ts
=> remove examples from public api

CHANGELOG.md, src/lib/components/component-collection.ts, src/lib/components/directive-collection.ts, src/lib/terra-components.module.ts
=> feature(public-api): remove private components/directives from the exports of the TerraComponentsModule

src/lib/components/forms/form/helper/terra-form.helper.ts
=> fix(terra-helper): remove duplicated code

CHANGELOG.md, package-lock.json, package.json, src/lib/components/forms/input/file-input/terra-file-input.component.spec.ts, src/lib/components/layouts/overlay/terra-overlay.component.spec.ts, src/lib/components/layouts/overlay/terra-overlay.component.ts, src/lib/package.json, src/lib/terra-components.module.ts
Testing
---
Documentation
Testing
=> feature (angular-update): update ngx-bootstrap

src/lib/components/forms/form/form-container/terra-form-container.component.spec.ts
=> fix (unit-test): terra form container

src/lib/components/layouts/tag/terra-tag.component.spec.ts
=> fix(tag): unit tests

src/lib/components/layouts/overlay/terra-overlay.component.spec.ts
=> fix(overlay): unit test

src/lib/components/forms/input/radio/radio-input.component.spec.ts
=> fix(radio-input): unit tests

src/lib/components/layouts/card/terra-card.component.spec.ts
=> fix(card): unit test

src/lib/components/layouts/portlet/terra-portlet.component.spec.ts
=> fix(portlet): unit test

src/lib/components/forms/input/color-picker/terra-color-picker.component.spec.ts
=> fix (unit-test): TerraColorPicker

src/lib/components/tables/data-table/table-row/table-row.component.spec.ts
=> fix(table-row): unit tests

src/lib/components/forms/input/double-input/terra-double-input.component.spec.ts
=> fix unit test

src/lib/utils/window.spec.ts
=> feature(utils): specs for window utility

src/lib/components/layouts/card/terra-card.component.spec.ts
=> fix(unit-test): terra card

.github/workflows/ci.yml
=> feature(ci): make the checks run on each pr

CHANGELOG.md, src/lib/styles/material/_form-field.scss
-   [x] Chrome
-   [x] Firefox
-   [x] Safari
Documentation
-   [x] Changelog
=> [Fix] Safari Bug for disabled inputs

.github/workflows/ci.yml
since they don't run concurrently as intended.
see:
https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/introduction-to-github-actions#jobs
https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/introduction-to-github-actions#steps
and
https://github.community/t/steps-in-parallel/16343
=> feature(ci): separate steps for the different checks

CHANGELOG.md, gulpfile.js, package-lock.json, package.json
=> feature(local build): delete terra-components folder in terra

CHANGELOG.md, src/lib/components/table/table-settings/table-settings.component.html, src/lib/terra-components.module.ts
=> replace terra button with mat button

CHANGELOG.md, src/lib/components/table/table-settings/dialog/table-settings-dialog.component.html
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
=> feature(setting overlay buttons): replace terra-button with mat-button.

CHANGELOG.md, src/lib/components/forms/form/helper/terra-form.helper.ts
=> fix assigning formControls to list form fields

CHANGELOG.md, src/lib/components/editors/code-editor/terra-code-editor.component.ts
@plentymarkets/ceres-io 
Testing
---
Documentation
=> added link to code-editor toolbar

src/lib/components/table/table-settings/table-settings.component.spec.ts
=> fix(table-settings): unit test

src/lib/components/alert/terra-alert-panel.component.ts, src/lib/components/data-picker/category-picker/terra-category-picker.component.ts, src/lib/components/file-browser/terra-file-browser.component.ts, src/lib/components/forms/checkbox-group/checkbox-group.component.ts, src/lib/components/forms/form/form-entry/terra-form-entry.component.ts, src/lib/components/forms/form/terra-form.component.ts, src/lib/components/stopwatch/terra-stopwatch.component.ts, src/lib/components/table/table-settings/table-settings.component.ts
=> remove empty scss files

src/lib/components/file-browser/file-list/file-list.component.ts
=> feature(file-list): use Array.map to extract keys instead

src/lib/components/tables/data-table/table-row/table-row.component.html, src/lib/components/tables/data-table/table-row/table-row.component.spec.ts, src/lib/components/tables/data-table/terra-data-table.component.html, src/lib/components/tables/data-table/terra-data-table.component.ts, src/lib/components/tables/simple/terra-simple-table.component.html, src/lib/components/tables/terra-base-table.spec.ts, src/lib/components/tables/terra-base-table.ts
Testing
-   [ ] Chrome
-   [ ] Safari
-   [ ] Chrome
-   [ ] Safari
---
Documentation
Testing
=> fix(terra-data-table): function of terra-checkbox in header and rows 

src/lib/utils/route-data.spec.ts, src/lib/utils/route-data.ts
Testing
---
Documentation
-   [ ] [Google spreadsheet](https://docs.google.com/spreadsheets/d/1OINnux8TEoitV-qdAxqUQaf9oGI_fqFVwfRWenRFfhI/edit#gid=0) (relevant when deprecating public APIs or features)
Testing
=> feature(route-data): utilities to extract route data from router config

src/lib/route-data/route-data-registry.spec.ts, src/lib/route-data/route-data-registry.ts, src/lib/route-data/utils/route-path.spec.ts, src/lib/route-data/utils/route-path.ts
Testing
---
Documentation
Testing
=> feature(route-data): implement `register` method

src/lib/route-data/route-data-registry.ts
Testing
---
Documentation
Testing
=> fix(route-data): normalize path when calling route data registry's registerOne-method directly

src/lib/route-data/index.ts, src/lib/route-data/route-data-registry.ts, src/lib/route-data/utils/route-path.spec.ts, src/lib/route-data/utils/route-path.ts
Testing
---
Documentation
Testing
=> feature(route-data): find matching route path for url

src/lib/route-data/route-data-registry.ts, src/lib/route-data/utils/routes.ts
Testing
---
Documentation
Testing
=> feature(route-data): handle redirected routes - option #1: "the extra property"

CHANGELOG.md, src/lib/components/tables/data-table/table-row/table-row.component.html, src/lib/components/tables/data-table/table-row/table-row.component.spec.ts, src/lib/components/tables/data-table/terra-data-table.component.html, src/lib/components/tables/data-table/terra-data-table.component.scss, src/lib/components/tables/data-table/terra-data-table.component.spec.ts, src/lib/terra-components.module.ts
Testing
-   [x] Chrome
-   [x] Firefox
-   [x] Safari
Responsiveness
-   [x] Desktop
-   [x] Tablet
-   [x] Mobile
-   [x] Chrome
-   [x] Firefox
-   [x] Safari
Responsiveness
-   [x] Desktop
-   [x] Tablet
-   [x] Mobile
---
Documentation
Testing
=> feature (data-table): use mat-checkbox

src/lib/components/breadcrumbs/service/terra-breadcrumbs.service.ts
=> feature(breadcrumbs): retrieve route data from routeDataRegistry if available

src/lib/route-data/index.ts
=> feature(route-data): add RouteData and ReadonlyRouteData to public api

src/lib/route-data/route-data-registry.spec.ts, src/lib/route-data/route-data-types.ts, src/lib/route-data/utils/routes.spec.ts
=> feature(route-data): Unit tests for redirected routes

src/lib/route/utils/route-children.spec.ts, src/lib/route/utils/route-children.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature(route-children): add unit test for undefined route

src/lib/route/index.ts
=> feature(route-data): export normalizeRoutePath

src/lib/route/data/route-data-registry.spec.ts, src/lib/route/data/route-data-registry.ts, src/lib/route/data/route-data-types.ts, src/lib/route/data/route-data.module.spec.ts, src/lib/route/data/route-data.module.ts, src/lib/route/index.ts, src/lib/route/utils/routes.spec.ts, src/lib/route/utils/routes.ts
Testing
---
Documentation
Testing
-   [X] Unit Test (updated or created)
=> feature(route-data): register data as an array

package-lock.json, package.json
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature (terra-icons): update to latest version

src/lib/route/data/route-data-registry.spec.ts, src/lib/route/data/route-data-registry.ts, src/lib/route/data/route-data-types.ts, src/lib/route/utils/routes.spec.ts, src/lib/route/utils/routes.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> fix(route): add a route to the other map only if it's path is empty

CHANGELOG.md, src/lib/components/table/table-settings/dialog/table-settings-dialog.component.html, src/lib/components/table/table-settings/dialog/table-settings-dialog.component.spec.ts, src/lib/components/table/table-settings/dialog/table-settings-dialog.component.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
Documentation
Testing
=> feature(tc-table-settings): hold position of column label after deselecting checkbox

package.json
=> change alias to npm ci in prepare-release

src/lib/components/table/table-settings/table-settings.component.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [x] Chrome
-   [ ] Safari
Responsiveness
-   [x] Desktop
-   [x] Tablet
-   [x] Mobile
=> feature(tc-table-settings): add second selector

CHANGELOG.md
=> fix(Changelog): table settings selector

.github/workflows/automerge_10_upwards.yml
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature(ci): add new plentymonkey user for merge

CHANGELOG.md, src/lib/components/table/table-settings/dialog/table-settings-dialog.component.ts, src/lib/components/table/table-settings/dialog/table-settings-dialog.glob.scss
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
Documentation
=> feature(table-settings): animate drag

package-lock.json
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> fix(vulnerability): more vulnerabilities

src/lib/components/forms/form/form-components/checkbox/checkbox.component.spec.ts, src/lib/components/forms/form/form-components/checkbox/checkbox.component.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
Testing
=> feature(Terra-Form): unit tests for the new checkbox

CHANGELOG.md, src/lib/components/forms/form/example/form-fields.ts, src/lib/components/forms/form/form-components/checkbox/checkbox.component.html, src/lib/components/forms/form/form-components/checkbox/checkbox.component.spec.ts, src/lib/components/forms/form/form-components/checkbox/checkbox.component.ts, src/lib/components/forms/form/model/form-type-map.ts, src/lib/terra-components.module.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> Feature (terraForm): Creating a wrapper Component for the checkbox

src/lib/components/component-collection.ts, src/lib/components/forms/form/form-components/text-input/text-input.component.spec.ts, src/lib/components/forms/form/form-components/text-input/text-input.component.ts, src/lib/components/forms/form/form-components/text-input/text-input.interface.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature(tests): basic tests

CHANGELOG.md, src/lib/components/component-collection.ts, src/lib/components/directive-collection.ts, src/lib/components/forms/form/example/form-fields.ts, src/lib/components/forms/form/form-components/text-input/text-input.component.html, src/lib/components/forms/form/form-components/text-input/text-input.component.spec.ts, src/lib/components/forms/form/form-components/text-input/text-input.component.ts, src/lib/components/forms/form/model/form-type-map.ts, src/lib/terra-components.module.ts, src/lib/validators/iban-validator.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature (Terra Form): Add wrapper component for the text input

src/lib/components/forms/form/form-components/datepicker/datepicker.component.spec.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> unit test for the datepicker

src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature (Terra Form): unit test for double input

src/lib/components/forms/form/example/form-fields.ts, src/lib/components/forms/form/form-components/color-picker/color-picker.component.html, src/lib/components/forms/form/form-components/color-picker/color-picker.component.scss, src/lib/components/forms/form/form-components/color-picker/color-picker.component.ts, src/lib/components/forms/form/model/form-type-map.ts, src/lib/terra-components.module.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> add color picker component

package-lock.json, package.json
=> fix(deps): 1 high severity vulnerability in karma

CHANGELOG.md, src/lib/components/forms/form/example/form-fields.ts, src/lib/components/forms/form/form-components/suggestion/suggestion.component.html, src/lib/components/forms/form/form-components/suggestion/suggestion.component.spec.ts, src/lib/components/forms/form/form-components/suggestion/suggestion.component.ts, src/lib/components/forms/form/form-components/suggestion/suggestion.interface.ts, src/lib/components/forms/form/model/form-type-map.ts, src/lib/components/forms/suggestion-box/data/terra-suggestion-box.interface.ts, src/lib/terra-components.module.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [x] …
=> feature(Terra-Form): replace terra-suggestions-box with mat-autocomplete

package-lock.json
=> fix(deps): security vulnerabilities for lodash and hosted-git-info

src/lib/components/file-browser/file-list/file-list.component.ts, src/lib/components/forms/form/form-container/terra-form-container.component.ts, src/lib/components/forms/form/form-entry-list/terra-form-entry-list.component.ts, src/lib/components/forms/form/form-entry/terra-form-entry.component.ts, src/lib/components/forms/form/helper/terra-form-field.helper.ts, src/lib/components/forms/form/helper/terra-form.helper.ts, src/lib/components/tables/data-table/terra-data-table.component.ts, src/lib/helpers/color.helper.ts, src/lib/utils/http-params.ts
I've replaced them with the recommendation from the deprecation notice of each function.
Testing
---
Documentation
=> feature: replace usages of some deprecated node utils (isNumber, isFunction, isObject, ...)

CHANGELOG.md, src/lib/components/layouts/portlet/terra-portlet.component.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [x] …
=> feature (Terra Portlet): deprecate terra portlet

CHANGELOG.md, src/lib/components/stopwatch/terra-stopwatch.component.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
Documentation
-   [x] JSDoc (optional: relevant for every change which influences the API)
-   [x] [Google …
=> feature(terra-stopwatch): deprecate terra-stopwatch

CHANGELOG.md, src/lib/components/tables/group-function/terra-group-function.component.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature(group-functions): deprecated

CHANGELOG.md, src/lib/components/forms/input/radio/radio-group.component.ts, src/lib/components/forms/input/radio/radio-input.component.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
Documentation
-   [x] [Google …
=> feature(terra-radio-group): deprecate radio group

CHANGELOG.md, src/lib/components/buttons/file-chooser/terra-file-chooser.component.ts
Testing
---
Documentation
-   [ ] [Google spreadsheet](https://docs.google.com/spreadsheets/d/1OINnux8TEoitV-qdAxqUQaf9oGI_fqFVwfRWenRFfhI/edit#gid=0) (relevant when deprecating public APIs or features)
Testing
=> feature(file-chooser): deprecate

src/lib/components/forms/form/form-components/multi-select/multi-select.component.html, src/lib/components/forms/form/form-components/multi-select/multi-select.component.spec.ts, src/lib/components/forms/form/form-components/multi-select/multi-select.component.ts, src/lib/components/forms/form/form-components/multi-select/pipes/pseudo-checkbox-state.pipe.spec.ts, src/lib/components/forms/form/form-components/multi-select/pipes/pseudo-checkbox-state.pipe.ts, src/lib/pipes/pipe-collection.ts, src/lib/terra-components.module.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature(form): multi select all

CHANGELOG.md, src/lib/components/table/terra-table-data-source.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature(table-data-source): add the stream searched

CHANGELOG.md, src/lib/components/forms/form/example/form-fields.ts, src/lib/components/forms/form/form-components/text-input/text-input.component.html, src/lib/components/forms/form/form-components/text-input/text-input.component.spec.ts, src/lib/components/forms/form/form-components/text-input/text-input.component.ts, src/lib/components/forms/form/form-components/text-input/text-input.interface.ts, src/lib/translations/l10n-terra-components.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature (form): Email validation with error message

CHANGELOG.md, src/app/app.component.html, src/lib/components/forms/form/example/form-fields.ts, src/lib/components/forms/form/form-components/text-area/text-area.component.html, src/lib/components/forms/form/form-components/text-area/text-area.component.spec.ts, src/lib/components/forms/form/form-components/text-area/text-area.component.ts, src/lib/components/forms/form/form-components/text-area/text-area.interface.ts, src/lib/components/forms/form/form-components/text-input/text-input.component.html, src/lib/components/forms/form/form-components/text-input/text-input.component.spec.ts, src/lib/components/forms/form/form-components/text-input/text-input.component.ts, src/lib/translations/l10n-terra-components.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> Feature/form validation/minlength maxlength

package-lock.json
=> fix(security vulnerabilites): 9 dependencies

CHANGELOG.md, src/lib/package.json
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> update version to 12.0.0-next.4

src/lib/components/file-browser/file-list/file-list.component.ts, src/lib/components/tables/data-table/table-row/table-row.component.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] JSDoc (optional: …
=> fix: remove host decorator since we use abstract classes

src/lib/components/filter/components/filter-toolbar/filter-toolbar.component.html
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature(filter): add ng-content

src/lib/components/tooltip/tooltip.directive.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> fix(tcToolTip): dynamicly enable tooltip text

CHANGELOG.md, src/lib/components/forms/form/form-container/terra-form-container--entry-list.component.ts, src/lib/components/forms/form/model/terra-form-field.interface.ts, src/lib/components/forms/form/terra-form.component.html, src/lib/components/forms/form/terra-form.component.spec.ts, src/lib/components/forms/form/terra-form.component.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> feature (terra-form): sort form fields by position

CHANGELOG.md, src/lib/package.json
Testing
---
Documentation
Testing
=> feature: update version to v12.0.0

package-lock.json
=> fix(security vulnerability): path-parse, tar and url-parse

package-lock.json, package.json
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> Update terra-lint-rules to ~1.0.2

CHANGELOG.md, src/lib/validators/iban-validator.spec.ts, src/lib/validators/iban-validator.ts, src/lib/validators/validators.spec.ts
Testing
---
Documentation
Testing
=> fix(validators): control with iban validator should be valid when its value is `null`, `undefined` or `''`

CHANGELOG.md, src/lib/components/forms/input/file-input/terra-file-input.component.html, src/lib/components/forms/input/file-input/terra-file-input.component.scss, src/lib/components/forms/input/file-input/terra-file-input.component.spec.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
- …
=> Revert #1647

CHANGELOG.md, src/lib/components/file-browser/data/terra-file-browser-node.interface.ts, src/lib/components/file-browser/file-list/file-list.component.ts, src/lib/components/file-browser/terra-file-browser.component.html, src/lib/components/file-browser/terra-file-browser.component.ts, src/lib/terra-components.module.ts
Reverts plentymarkets/terra-components#1651
=> Revert "feature (file-browser): exchange old tree with mat-tree"

CHANGELOG.md, src/lib/components/file-browser/image-preview/image-preview.component.html, src/lib/components/file-browser/image-preview/image-preview.component.ts, src/lib/terra-components.module.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
- …
=> revert changes to image-preview

CHANGELOG.md, src/lib/components/file-browser/image-preview/image-preview.component.html, src/lib/components/file-browser/image-preview/image-preview.component.ts, src/lib/terra-components.module.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
- …
=> feature(image-preview): materialize

CHANGELOG.md, src/lib/components/file-browser/data/terra-file-browser-node.interface.ts, src/lib/components/file-browser/file-list/file-list.component.ts, src/lib/components/file-browser/terra-file-browser.component.html, src/lib/components/file-browser/terra-file-browser.component.ts, src/lib/terra-components.module.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
- …
=> feature(file-browser): materialize

CHANGELOG.md, src/lib/components/forms/input/file-input/terra-file-input.component.html, src/lib/components/forms/input/file-input/terra-file-input.component.scss, src/lib/components/forms/input/file-input/terra-file-input.component.spec.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
- …
=> Upgrade file-input-component with material

src/lib/components/tree/node-tree/example/terra-node-tree.component.example.ts, src/lib/components/tree/node-tree/node/pipe/is-icon-object.pipe.ts, src/lib/components/tree/node-tree/node/terra-node.component.html, src/lib/components/tree/node-tree/node/terra-node.component.scss, src/lib/pipes/pipe-collection.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
- …
=> feature (node-tree): add mat icons support

CHANGELOG.md, src/lib/components/directive-collection.ts, src/lib/components/filter/components/filter-toolbar/filter-toolbar.component.html, src/lib/components/filter/components/filter-toolbar/filter-toolbar.component.spec.ts, src/lib/components/filter/components/filter-toolbar/filter-toolbar.component.ts, src/lib/components/filter/filter.module.ts, src/lib/components/tooltip/terra-tooltip.module.ts, src/lib/components/tooltip/tooltip.module.ts, src/lib/public-api.ts, src/lib/terra-components.module.ts, src/lib/translations/l10n-terra-components.ts
+ add TooltipDirective to module and to publicApi
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Please inform a member of Terra (@plentymarkets/team-terra) to get the upper part of the …
=> feature (filter-toolbar): add missing tooltips and creating module for tooltip directive

src/lib/components/filter/_filter.scss
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [x] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
- …
=> feature(filter-menu): Added divider in filter menu

CHANGELOG.md, src/lib/components/buttons/file-chooser/terra-file-chooser.component.html, src/lib/components/buttons/file-chooser/terra-file-chooser.component.scss, src/lib/components/buttons/file-chooser/terra-file-chooser.component.ts, src/lib/components/file-browser/file-list/file-list.component.scss, src/lib/components/file-browser/image-preview/image-preview.component.scss
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
- …
=> feature(file-chooser): replace terra portlet by mat dialog

src/lib/components/table/table-settings/dialog/table-settings-dialog.component.html
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
- …
=> Feature(table-settings-dialog): Change confirm button color to active

gulp.config.js, gulpfile.js, src/lib/package.json
Reverts plentymarkets/terra-components#1675
=> Revert "feature(build): leverage ng-packagr instead of gulp to copy needed assets"

README.md
=> Lib: Pull the plug
