plentymarkets/terra-components

src/app/forms/checkbox/terra-checkbox.component.ts
- add output for two way binding (naming valueChange is necessary)
- set isIndeterminate via private var and not setter, otherwise _innerValue is always false
=> fix checkbox data binding

src/app/forms/select-box/terra-select-box.component.html, src/app/forms/select-box/terra-select-box.component.ts, src/app/forms/suggestion-box/terra-suggestion-box.component.ts, src/app/table/data-table/context-menu/terra-data-table-context-menu.component.ts
* Do not register HostListener to the document for every select box component.
* Instead register EventListener only when the dropdown is opened.
* Remove added EventListener afterwards to prevent ChangeDetection to be fired
* also replace host listeners in "terra-suggestion-box" and "terra-data-table-context-menu" with dynamically attached EventListeners
=> fix: replace global hostlisteners for select-box, suggestion-box and data-table-context menu

src/app/split-view/multi/data/terra-multi-split-view.config.ts, src/app/split-view/multi/terra-multi-split-view.component.ts
fix ExpressionChangedAfterItHasBeenCheckedError which is thrown on adding the contact details view right after the menu without change detection being executed in between.
* no change detection fired because the click handler of the action menu button "contact" has been executed without firing the click event
* setTimeout on adding a view triggers change detection instead
=> fix: ExpressionChangedAfterItHasBeenCheckedError..

CHANGELOG.md, src/app/split-view/multi/terra-multi-split-view.component.ts
when removing a view, that is not vertically selected (rendered).
Includes some robustness enhancements.
=> fix: removing subsequent breadcrumbs..

gulpfile.js
@nappynapster @MFrank84 
Erlaubt die Angabe eines Ziel-Projekts, um die Terra-Components zu kopieren:
```
npm run build -- --target /PATH/TO/PROJECT
```
=> Kopiert die build-files nach `/PATH/TO/PROJECT/node_modules/@plentymarkets/terra-components`
=> Allow target parameter when building terra-components

CHANGELOG.md, src/app/split-view/multi/terra-multi-split-view.component.ts
..the generic solution
**new inputs**
- `inputRouter`: pass the angular router to access the route config and its events
- `inputComponentRoute`: state the route of the component, that instantiates the split-view
=> feature: (multi-split-view) refocus selected view on tab switch

src/app/portlet/terra-portlet.component.scss
@felixdausch: du hattest die Zeile eingebaut. leider wird das Drop-Down der Select Box in einem Portlet nicht mehr angezeigt. siehst du eine andere Lösung für den Anwendungsfalls, für den du das overflow eingebaut hast?
@vwiebe, @zakpur
=> FIX show drop down of select box which is used in portlet

CHANGELOG.md, src/app/split-view/multi/data/terra-multi-split-view.config.ts
* disable public access to the data model, since it shouldn't be edited manually
=> feature (multi-split-view): restrict public data model access

src/app/forms/select-box/terra-select-box.component.ts, src/app/forms/suggestion-box/terra-suggestion-box.component.ts
Siehe commit https://github.com/plentymarkets/terra-components/commit/856eee97d5683795a797039ee1b8ee7075826b9b#diff-bccd4520ce42140ff02219085af8e7ee
```
-           && this.inputListBoxValues.indexOf(this._selectedValue) == -1)
+           && this.inputListBoxValues.find((x) => this._selectedValue === x))
```
Vorher `== -1` also wenn **nicht** gefunden. Nach dem change dann **true** nur **wenn gefunden**
=> FIX - select default value

src/app/info-box/terra-info-box.component.scss
Statt form elements direkt in eine table zu packen, sollen wir auf die info-box ausweichen...
Geht leider bei select-box nicht da overflow hidden auf alle divs gesetzt war. Dadurch werden absolut positionierte Elemente nicht mehr angezeigt, unter anderem das dropdown der select-box.
Ich habe das overflow hidden nun aus dem div selector entfernt und statt dessen einer liste von text elementen hinzugefügt.
=> FIX - overflow infobox

CHANGELOG.md, src/app/table/data-table/terra-data-table.component.scss, src/app/table/simple/row/terra-simple-table-row.interface.ts, src/app/table/simple/terra-simple-table.component.html, src/app/table/simple/terra-simple-table.component.ts
Additionally set option `disabled` in `TerraSimpleTableRowInterface` to disable a single table row.
- When having `inputUseHighlighting` disabled rows may not be highlighted. Clicking a row will emit `outputRowClicked` but not `outputHighlightedRowChange`
- When having `inputEnableHotkeys` disabled rows will be skipped.
- When having `inputHasCheckbox`, checkboxes of disabled rows will be disabled too.
- When having `inputHasCheckbox` the header checkbox will not affect checkboxes of disabled rows.
- When having Buttons defined in `TerraSimpleTableRowInterface.cellList.buttonList` all buttons will be disabled.
see: https://github.com/plentymarkets/terra/pull/411
=> ADD option to disable single rows in simple-table

src/app/table/data-table/terra-data-table.component.html, src/app/table/data-table/terra-data-table.component.ts
- fixed bug that occurred when table has not loaded yet but header checkbox is clicked. The event triggered the row iteration which at that point was an null object causing errors
- fixed display bug that occurred when inputHasCheckbox value was given but table has not loaded yet. The header checkbox was shown although table content was not loaded.
=> TerraDataTable bug fixes

CHANGELOG.md, src/app/components/tables/data-table/terra-data-table.component.scss
... use blue highlight color instead
=> fix (data-table): remove underline text decoration for href elements

src/app/components/split-view/multi/data/terra-multi-split-view.config.ts
... in order to be able to reuse components in different split views.
=> feature (split-view): make the config injectable

CHANGELOG.md, src/app/components/forms/suggestion-box/example/terra-suggestion-box.component.example.html, src/app/components/forms/suggestion-box/example/terra-suggestion-box.component.example.ts, src/app/components/forms/suggestion-box/terra-suggestion-box.component.html, src/app/components/forms/suggestion-box/terra-suggestion-box.component.ts
This PR actually includes various improvements:
* New Output `textInputValueChange` that emits the current text input value
* Select a Value from the suggestions if the entered text matches its caption
* `selectedValue` is reset if `inputListBoxValues` is updated and the previous selected element is not present anymore
* `selectedValue = null` if entered text does not match any of the `inputListBoxValues`
* `resetComponentValue`-Method is now deprecated. Use `ngModel` instead to set the value to `null`
* `outputValueChanged` is now deprecated. Use `ngModelChange` instead.
=> feature (suggestion-box): get text input value and reset selection

src/app/components/tree/node-tree/data/terra-node-tree.config.ts
Currently there is a compilation error with beta7..
Testing
In Order to test this you need to switch to the branch https://github.com/plentymarkets/terra-components/tree/fix/node-tree_config/access_modifier_translation_beta_3.0.0 and temporarily adjust the constructor of the `SystemTreeConfig` in Terra on beta7 =>
```
constructor(private router:Router,
translation:TranslationService,
private permissionsService:PermissionsService,
private systemPermissionsService:SystemPermissionsService,
private globalRegistry:GlobalRegistryService,
private keywordsService:SystemKeywordsService)
{
super(translation);
this.pluginNodes = [];
this.routeConfig = this.router.config as TerraRoutes;
}
```
=> fix (terra-node-tree.config): issue with access modifier in extended classes

src/app/components/layouts/column-container/two-columns/terra-two-columns-container.component.spec.ts
=> fix (two-column-container): prevent console output in unit tests

CHANGELOG.md, src/app/components/forms/select-box/terra-select-box.component.scss
=> fix(terra-select-box):fixed broken padding on compact mode

CHANGELOG.md, src/app/components/forms/multi-check-box/terra-multi-check-box.component.html, src/app/components/forms/multi-check-box/terra-multi-check-box.component.ts
add trackBy function to resolve performance issue with large valueLists (~100+ entries)
Documentation
Testing
=> fix(multi-check-box): add trackBy function to resolve performance issue

src/app/http-interceptors/auth.interceptor.spec.ts, src/app/http-interceptors/auth.interceptor.ts
=> fix(http): prevent AuthInterceptor from adding Authorization to the header if the accessToken is not set

src/lib/components/tree/node-tree/data/terra-node-tree.config.ts
...since it is not backwards compatible. When trying to install the latest release in terra the following error occurs:
=> fix(node-tree): access modifier for TranslationService

CHANGELOG.md, src/lib/components/buttons/toggle/terra-toggle.component.scss
=> feature(terra-toggle-component):added color to disabled state

CHANGELOG.md, src/lib/components/layouts/portlet/terra-portlet.component.scss
Testing
Documentation
Vorher
Nachher
=> [FIX] Removed negative margins from container that are nested in a portlets

CHANGELOG.md, src/lib/components/file-browser/file-list/file-list.component.ts, src/lib/components/file-browser/terra-file-browser.component.html, src/lib/components/file-browser/terra-file-browser.component.ts
Also removed forwardRef that was only needed to break the circular dependency..
Testing
----
Documentation
=> fix(circular dependency): terra-file-browser.ts <-> file-list.component.ts

CHANGELOG.md, src/lib/components/layouts/portlet/terra-portlet.component.scss
Testing
Responsiveness
Responsiveness
Documentation
=> fix(terra-portlet):remove overflow

package-lock.json
It was "high severity".
Executed `npm update http-proxy --depth 4` based on the recommendation of `npm audit`
=> fix(deps): updated http-proxy to v1.18.1 to resolve security vulnerability

README.md, gulpfile.js, karma.conf.js, package.json
Using this badge generator: https://shields.io/category/coverage
Running `npm run badge:coverage` prints a badge to our README.md with the latest coverage.
=> feature: code coverage badge for README

CHANGELOG.md, src/lib/components/tree/node-tree/node/terra-node.component.scss
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
Documentation
=> fix (terra-node): remove margin to reduce overflow in terra-node-tree

src/lib/components/forms/form/form-components/checkbox/checkbox.component.html, src/lib/components/forms/form/form-components/checkbox/checkbox.component.spec.ts, src/lib/components/forms/form/form-components/checkbox/checkbox.component.ts
Unfortunately, the checkbox can not be used within an angular material form-field. (see https://github.com/angular/components/issues/7891 for further information)
Hence, the error message will simply be shown below the checkbox, as it can be seen in the following screenshot:
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Inform Ceres about changes in `TerraFormComponent` (optional: relevant for changes in this …
=> feature(form): required true validation error message

CHANGELOG.md, src/lib/components/forms/form/example/form-fields.ts, src/lib/components/forms/form/form-entry/terra-form-entry.base.ts
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Documentation
-   [ ] …
=> fix(form): support legacy input names on new form components

gulp.config.js, gulpfile.js, src/lib/package.json
See: https://github.com/ng-packagr/ng-packagr/blob/master/docs/copy-assets.md
Testing
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
-   [ ] Chrome
-   [ ] Safari
Responsiveness
-   [ ] Tablet
-   [ ] Mobile
---
Please inform a member of Terra (@plentymarkets/team-terra) to get …
=> feature(build): leverage ng-packagr instead of gulp to copy needed assets
